<?php

namespace Database\Seeders;

use App\Models\SubCity;
use Illuminate\Database\Seeder;

class SubCitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $subCities = [
            [
                'name' => 'Addis Ketema Sub-City',
                'code' => 'ADDIS_KETEMA',
                'description' => 'Addis Ketema is one of the central sub-cities of Addis Ababa, known for its large commercial areas, markets, and high economic activity. It hosts key trading centers and serves as a major hub for small and medium enterprises.',
                'address' => 'Addis Ketema, Addis Ababa',
                'phone' => '+251900000001',
                'email' => 'admin@itdb.gov.et',
                'website' => 'https://addisketemasubcity.gov.et',
                'logo' => null,
                'admin_name' => 'ITDB Administrator',
                'admin_email' => 'admin@itdb.gov.et',
                'admin_phone' => '+251900000001',
                'is_active' => true,
                'activated_at' => now(),
                'deactivated_at' => null,
                'subscription_tier' => 'basic',
                'subscription_expires_at' => null,
            ],
            [
                'name' => 'Akaky Kaliti Sub-City',
                'code' => 'AKAKY_KALITI',
                'description' => 'Akaky Kaliti is an industrial and residential sub-city of Addis Ababa, hosting factories, warehouses, and expanding housing developments. It plays a key role in the city\'s manufacturing and logistics sector.',
                'address' => 'Akaky Kaliti, Addis Ababa',
                'phone' => '+251900000002',
                'email' => 'admin@itdb.gov.et',
                'website' => 'https://akakykalitisubcity.gov.et',
                'logo' => null,
                'admin_name' => 'ITDB Administrator',
                'admin_email' => 'admin@itdb.gov.et',
                'admin_phone' => '+251900000002',
                'is_active' => true,
                'activated_at' => now(),
                'deactivated_at' => null,
                'subscription_tier' => 'basic',
                'subscription_expires_at' => null,
            ],
            [
                'name' => 'Arada Sub-City',
                'code' => 'ARADA',
                'description' => 'Arada is one of the oldest and most historic sub-cities in Addis Ababa, home to cultural institutions, government offices, and educational centers. It is a central area with significant administrative importance.',
                'address' => 'Arada, Addis Ababa',
                'phone' => '+251900000003',
                'email' => 'admin@itdb.gov.et',
                'website' => 'https://aradasubcity.gov.et',
                'logo' => null,
                'admin_name' => 'ITDB Administrator',
                'admin_email' => 'admin@itdb.gov.et',
                'admin_phone' => '+251900000003',
                'is_active' => true,
                'activated_at' => now(),
                'deactivated_at' => null,
                'subscription_tier' => 'basic',
                'subscription_expires_at' => null,
            ],
            [
                'name' => 'Bole Sub-City',
                'code' => 'BOLE',
                'description' => 'Bole is a vibrant area known for its diverse community. It serves as a key governmental institution, encompassing ten woredas that provide essential public services, including education and healthcare.

Its strategic location and comprehensive services highlight its significance in Addis Ababa\'s urban landscape. Bole is dedicated to community development, contributing significantly to the city\'s growth and advancement.',
                'address' => 'Bole-Megenagna, Addis Ababa',
                'phone' => '+251924548968',
                'email' => 'admin@itdb.gov.et',
                'website' => 'https://bolesubcity.com/about',
                'logo' => null,
                'admin_name' => 'Haregewoin Menberu',
                'admin_email' => 'hre4422@gmail.com',
                'admin_phone' => '+251924548968',
                'is_active' => true,
                'activated_at' => now(),
                'deactivated_at' => null,
                'subscription_tier' => 'basic',
                'subscription_expires_at' => null,
            ],
            [
                'name' => 'Gullele Sub-City',
                'code' => 'GULLELE',
                'description' => 'Gullele is a green and mountainous sub-city of Addis Ababa, known for its natural environment and proximity to Gullele Botanical Garden. It plays a key role in environmental conservation and urban ecology.',
                'address' => 'Gullele, Addis Ababa',
                'phone' => '+251900000005',
                'email' => 'admin@itdb.gov.et',
                'website' => 'https://gullelesubcity.gov.et',
                'logo' => null,
                'admin_name' => 'ITDB Administrator',
                'admin_email' => 'admin@itdb.gov.et',
                'admin_phone' => '+251900000005',
                'is_active' => true,
                'activated_at' => now(),
                'deactivated_at' => null,
                'subscription_tier' => 'basic',
                'subscription_expires_at' => null,
            ],
            [
                'name' => 'Kirkos Sub-City',
                'code' => 'KIRKOS',
                'description' => 'Kirkos is a centrally located sub-city in Addis Ababa with a mix of residential, business, and governmental institutions. It is an important administrative and commercial area.',
                'address' => 'Kirkos, Addis Ababa',
                'phone' => '+251900000006',
                'email' => 'admin@itdb.gov.et',
                'website' => 'https://kirkossubcity.gov.et',
                'logo' => null,
                'admin_name' => 'ITDB Administrator',
                'admin_email' => 'admin@itdb.gov.et',
                'admin_phone' => '+251900000006',
                'is_active' => true,
                'activated_at' => now(),
                'deactivated_at' => null,
                'subscription_tier' => 'basic',
                'subscription_expires_at' => null,
            ],
            [
                'name' => 'Kolfe Keranio Sub-City',
                'code' => 'KOLFE_KERANIO',
                'description' => 'Kolfe Keranio is one of the largest sub-cities in Addis Ababa, featuring both urban and peri-urban settlements. It is known for housing developments and expanding infrastructure.',
                'address' => 'Kolfe Keranio, Addis Ababa',
                'phone' => '+251900000007',
                'email' => 'admin@itdb.gov.et',
                'website' => 'https://kolfekeraniosubcity.gov.et',
                'logo' => null,
                'admin_name' => 'ITDB Administrator',
                'admin_email' => 'admin@itdb.gov.et',
                'admin_phone' => '+251900000007',
                'is_active' => true,
                'activated_at' => now(),
                'deactivated_at' => null,
                'subscription_tier' => 'basic',
                'subscription_expires_at' => null,
            ],
            [
                'name' => 'Lideta Sub-City',
                'code' => 'LIDETA',
                'description' => 'Lideta is a compact and centrally located sub-city known for administrative offices, residential areas, and business activities. It plays an important role in city governance and services.',
                'address' => 'Lideta, Addis Ababa',
                'phone' => '+251900000008',
                'email' => 'admin@itdb.gov.et',
                'website' => 'https://lidetasubcity.gov.et',
                'logo' => null,
                'admin_name' => 'ITDB Administrator',
                'admin_email' => 'admin@itdb.gov.et',
                'admin_phone' => '+251900000008',
                'is_active' => true,
                'activated_at' => now(),
                'deactivated_at' => null,
                'subscription_tier' => 'basic',
                'subscription_expires_at' => null,
            ],
            [
                'name' => 'Nifas Silk-Lafto Sub-City',
                'code' => 'NIFAS_SILK_LAFTO',
                'description' => 'Nifas Silk-Lafto is a large residential sub-city in Addis Ababa, featuring growing urban development, housing projects, and public services infrastructure.',
                'address' => 'Nifas Silk-Lafto, Addis Ababa',
                'phone' => '+251900000009',
                'email' => 'admin@itdb.gov.et',
                'website' => 'https://nifassilklaftosubcity.gov.et',
                'logo' => null,
                'admin_name' => 'ITDB Administrator',
                'admin_email' => 'admin@itdb.gov.et',
                'admin_phone' => '+251900000009',
                'is_active' => true,
                'activated_at' => now(),
                'deactivated_at' => null,
                'subscription_tier' => 'basic',
                'subscription_expires_at' => null,
            ],
            [
                'name' => 'Yeka Sub-City',
                'code' => 'YEKA',
                'description' => 'Yeka is a rapidly developing sub-city in Addis Ababa, known for its residential neighborhoods, hills, and expanding urban infrastructure. It is a key area for modern housing projects.',
                'address' => 'Yeka, Addis Ababa',
                'phone' => '+251900000010',
                'email' => 'admin@itdb.gov.et',
                'website' => 'https://yekasubcity.gov.et',
                'logo' => null,
                'admin_name' => 'ITDB Administrator',
                'admin_email' => 'admin@itdb.gov.et',
                'admin_phone' => '+251900000010',
                'is_active' => true,
                'activated_at' => now(),
                'deactivated_at' => null,
                'subscription_tier' => 'basic',
                'subscription_expires_at' => null,
            ],
            [
                'name' => 'Lemi Kura Sub-City',
                'code' => 'LEMI_KURA',
                'description' => 'Lemi Kura is the newest sub-city in Addis Ababa, created to manage the rapidly expanding urban population and development in the eastern part of the city. It focuses on infrastructure expansion and urban planning.',
                'address' => 'Lemi Kura, Addis Ababa',
                'phone' => '+251900000011',
                'email' => 'admin@itdb.gov.et',
                'website' => 'https://lemikurasubcity.gov.et',
                'logo' => null,
                'admin_name' => 'ITDB Administrator',
                'admin_email' => 'admin@itdb.gov.et',
                'admin_phone' => '+251900000011',
                'is_active' => true,
                'activated_at' => now(),
                'deactivated_at' => null,
                'subscription_tier' => 'basic',
                'subscription_expires_at' => null,
            ],
        ];

        foreach ($subCities as $subCity) {
            SubCity::updateOrCreate(
                ['code' => $subCity['code']],
                $subCity
            );
        }

        $this->command->info('✓ Sub-cities seeded successfully!');
    }
}
