/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as SubCitiesRouteImport } from './routes/sub-cities'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstitutionRegisterRouteImport } from './routes/institution-register'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeasibilityRouteImport } from './routes/feasibility'
import { Route as DuplicationRouteImport } from './routes/duplication'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CybersecurityRouteImport } from './routes/cybersecurity'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as SubCitiesIndexRouteImport } from './routes/sub-cities.index'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as RegistryIndexRouteImport } from './routes/registry.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as VendorsCreateRouteImport } from './routes/vendors.create'
import { Route as UsersCreateRouteImport } from './routes/users.create'
import { Route as SubCitiesCreateRouteImport } from './routes/sub-cities.create'
import { Route as SubCitiesIdRouteImport } from './routes/sub-cities.$id'
import { Route as ServicesServiceSlugRouteImport } from './routes/services.$serviceSlug'
import { Route as ResearchTransfersRouteImport } from './routes/research.transfers'
import { Route as ResearchScreeningsRouteImport } from './routes/research.screenings'
import { Route as ResearchReportsRouteImport } from './routes/research.reports'
import { Route as ResearchProjectsRouteImport } from './routes/research.projects'
import { Route as ResearchIdeasRouteImport } from './routes/research.ideas'
import { Route as ResearchEvaluationsRouteImport } from './routes/research.evaluations'
import { Route as RequestsCreateRouteImport } from './routes/requests.create'
import { Route as RegistryCreateRouteImport } from './routes/registry.create'
import { Route as SubCitiesIdIndexRouteImport } from './routes/sub-cities.$id.index'
import { Route as UsersIdEditRouteImport } from './routes/users.$id.edit'
import { Route as SubCitiesIdEditRouteImport } from './routes/sub-cities.$id.edit'
import { Route as ResearchProjectsIdRouteImport } from './routes/research.projects.$id'
import { Route as ResearchIdeasCreateRouteImport } from './routes/research.ideas.create'
import { Route as ResearchIdeasIdRouteImport } from './routes/research.ideas.$id'
import { Route as RequestsIdEditRouteImport } from './routes/requests.$id.edit'
import { Route as RegistryIdEditRouteImport } from './routes/registry.$id.edit'
import { Route as ResearchTransfersCreateProjectIdRouteImport } from './routes/research.transfers.create.$projectId'
import { Route as ResearchScreeningsCreateIdeaIdRouteImport } from './routes/research.screenings.create.$ideaId'
import { Route as ResearchProjectsCreateIdeaIdRouteImport } from './routes/research.projects.create.$ideaId'
import { Route as ResearchIdeasIdEditRouteImport } from './routes/research.ideas.$id.edit'
import { Route as ResearchEvaluationsCreateProjectIdRouteImport } from './routes/research.evaluations.create.$projectId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const SubCitiesRoute = SubCitiesRouteImport.update({
  id: '/sub-cities',
  path: '/sub-cities',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionRegisterRoute = InstitutionRegisterRouteImport.update({
  id: '/institution-register',
  path: '/institution-register',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeasibilityRoute = FeasibilityRouteImport.update({
  id: '/feasibility',
  path: '/feasibility',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicationRoute = DuplicationRouteImport.update({
  id: '/duplication',
  path: '/duplication',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CybersecurityRoute = CybersecurityRouteImport.update({
  id: '/cybersecurity',
  path: '/cybersecurity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorsRoute,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const SubCitiesIndexRoute = SubCitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubCitiesRoute,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequestsRoute,
} as any)
const RegistryIndexRoute = RegistryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegistryRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotificationsRoute,
} as any)
const VendorsCreateRoute = VendorsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => VendorsRoute,
} as any)
const UsersCreateRoute = UsersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => UsersRoute,
} as any)
const SubCitiesCreateRoute = SubCitiesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SubCitiesRoute,
} as any)
const SubCitiesIdRoute = SubCitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SubCitiesRoute,
} as any)
const ServicesServiceSlugRoute = ServicesServiceSlugRouteImport.update({
  id: '/services/$serviceSlug',
  path: '/services/$serviceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchTransfersRoute = ResearchTransfersRouteImport.update({
  id: '/research/transfers',
  path: '/research/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchScreeningsRoute = ResearchScreeningsRouteImport.update({
  id: '/research/screenings',
  path: '/research/screenings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchReportsRoute = ResearchReportsRouteImport.update({
  id: '/research/reports',
  path: '/research/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchProjectsRoute = ResearchProjectsRouteImport.update({
  id: '/research/projects',
  path: '/research/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIdeasRoute = ResearchIdeasRouteImport.update({
  id: '/research/ideas',
  path: '/research/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchEvaluationsRoute = ResearchEvaluationsRouteImport.update({
  id: '/research/evaluations',
  path: '/research/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsCreateRoute = RequestsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => RequestsRoute,
} as any)
const RegistryCreateRoute = RegistryCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => RegistryRoute,
} as any)
const SubCitiesIdIndexRoute = SubCitiesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubCitiesIdRoute,
} as any)
const UsersIdEditRoute = UsersIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => UsersRoute,
} as any)
const SubCitiesIdEditRoute = SubCitiesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SubCitiesIdRoute,
} as any)
const ResearchProjectsIdRoute = ResearchProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResearchProjectsRoute,
} as any)
const ResearchIdeasCreateRoute = ResearchIdeasCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ResearchIdeasRoute,
} as any)
const ResearchIdeasIdRoute = ResearchIdeasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResearchIdeasRoute,
} as any)
const RequestsIdEditRoute = RequestsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => RequestsRoute,
} as any)
const RegistryIdEditRoute = RegistryIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => RegistryRoute,
} as any)
const ResearchTransfersCreateProjectIdRoute =
  ResearchTransfersCreateProjectIdRouteImport.update({
    id: '/create/$projectId',
    path: '/create/$projectId',
    getParentRoute: () => ResearchTransfersRoute,
  } as any)
const ResearchScreeningsCreateIdeaIdRoute =
  ResearchScreeningsCreateIdeaIdRouteImport.update({
    id: '/create/$ideaId',
    path: '/create/$ideaId',
    getParentRoute: () => ResearchScreeningsRoute,
  } as any)
const ResearchProjectsCreateIdeaIdRoute =
  ResearchProjectsCreateIdeaIdRouteImport.update({
    id: '/create/$ideaId',
    path: '/create/$ideaId',
    getParentRoute: () => ResearchProjectsRoute,
  } as any)
const ResearchIdeasIdEditRoute = ResearchIdeasIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ResearchIdeasIdRoute,
} as any)
const ResearchEvaluationsCreateProjectIdRoute =
  ResearchEvaluationsCreateProjectIdRouteImport.update({
    id: '/create/$projectId',
    path: '/create/$projectId',
    getParentRoute: () => ResearchEvaluationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/cybersecurity': typeof CybersecurityRoute
  '/dashboard': typeof DashboardRoute
  '/duplication': typeof DuplicationRoute
  '/feasibility': typeof FeasibilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/institution-register': typeof InstitutionRegisterRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/registry': typeof RegistryRouteWithChildren
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sub-cities': typeof SubCitiesRouteWithChildren
  '/surveys': typeof SurveysRoute
  '/users': typeof UsersRouteWithChildren
  '/vendors': typeof VendorsRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/registry/create': typeof RegistryCreateRoute
  '/requests/create': typeof RequestsCreateRoute
  '/research/evaluations': typeof ResearchEvaluationsRouteWithChildren
  '/research/ideas': typeof ResearchIdeasRouteWithChildren
  '/research/projects': typeof ResearchProjectsRouteWithChildren
  '/research/reports': typeof ResearchReportsRoute
  '/research/screenings': typeof ResearchScreeningsRouteWithChildren
  '/research/transfers': typeof ResearchTransfersRouteWithChildren
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/sub-cities/$id': typeof SubCitiesIdRouteWithChildren
  '/sub-cities/create': typeof SubCitiesCreateRoute
  '/users/create': typeof UsersCreateRoute
  '/vendors/create': typeof VendorsCreateRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/registry/': typeof RegistryIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/sub-cities/': typeof SubCitiesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/registry/$id/edit': typeof RegistryIdEditRoute
  '/requests/$id/edit': typeof RequestsIdEditRoute
  '/research/ideas/$id': typeof ResearchIdeasIdRouteWithChildren
  '/research/ideas/create': typeof ResearchIdeasCreateRoute
  '/research/projects/$id': typeof ResearchProjectsIdRoute
  '/sub-cities/$id/edit': typeof SubCitiesIdEditRoute
  '/users/$id/edit': typeof UsersIdEditRoute
  '/sub-cities/$id/': typeof SubCitiesIdIndexRoute
  '/research/evaluations/create/$projectId': typeof ResearchEvaluationsCreateProjectIdRoute
  '/research/ideas/$id/edit': typeof ResearchIdeasIdEditRoute
  '/research/projects/create/$ideaId': typeof ResearchProjectsCreateIdeaIdRoute
  '/research/screenings/create/$ideaId': typeof ResearchScreeningsCreateIdeaIdRoute
  '/research/transfers/create/$projectId': typeof ResearchTransfersCreateProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/cybersecurity': typeof CybersecurityRoute
  '/dashboard': typeof DashboardRoute
  '/duplication': typeof DuplicationRoute
  '/feasibility': typeof FeasibilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/institution-register': typeof InstitutionRegisterRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/surveys': typeof SurveysRoute
  '/workflows': typeof WorkflowsRoute
  '/registry/create': typeof RegistryCreateRoute
  '/requests/create': typeof RequestsCreateRoute
  '/research/evaluations': typeof ResearchEvaluationsRouteWithChildren
  '/research/ideas': typeof ResearchIdeasRouteWithChildren
  '/research/projects': typeof ResearchProjectsRouteWithChildren
  '/research/reports': typeof ResearchReportsRoute
  '/research/screenings': typeof ResearchScreeningsRouteWithChildren
  '/research/transfers': typeof ResearchTransfersRouteWithChildren
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/sub-cities/create': typeof SubCitiesCreateRoute
  '/users/create': typeof UsersCreateRoute
  '/vendors/create': typeof VendorsCreateRoute
  '/notifications': typeof NotificationsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/registry': typeof RegistryIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/sub-cities': typeof SubCitiesIndexRoute
  '/users': typeof UsersIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/registry/$id/edit': typeof RegistryIdEditRoute
  '/requests/$id/edit': typeof RequestsIdEditRoute
  '/research/ideas/$id': typeof ResearchIdeasIdRouteWithChildren
  '/research/ideas/create': typeof ResearchIdeasCreateRoute
  '/research/projects/$id': typeof ResearchProjectsIdRoute
  '/sub-cities/$id/edit': typeof SubCitiesIdEditRoute
  '/users/$id/edit': typeof UsersIdEditRoute
  '/sub-cities/$id': typeof SubCitiesIdIndexRoute
  '/research/evaluations/create/$projectId': typeof ResearchEvaluationsCreateProjectIdRoute
  '/research/ideas/$id/edit': typeof ResearchIdeasIdEditRoute
  '/research/projects/create/$ideaId': typeof ResearchProjectsCreateIdeaIdRoute
  '/research/screenings/create/$ideaId': typeof ResearchScreeningsCreateIdeaIdRoute
  '/research/transfers/create/$projectId': typeof ResearchTransfersCreateProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/cybersecurity': typeof CybersecurityRoute
  '/dashboard': typeof DashboardRoute
  '/duplication': typeof DuplicationRoute
  '/feasibility': typeof FeasibilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/institution-register': typeof InstitutionRegisterRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/registry': typeof RegistryRouteWithChildren
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sub-cities': typeof SubCitiesRouteWithChildren
  '/surveys': typeof SurveysRoute
  '/users': typeof UsersRouteWithChildren
  '/vendors': typeof VendorsRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/registry/create': typeof RegistryCreateRoute
  '/requests/create': typeof RequestsCreateRoute
  '/research/evaluations': typeof ResearchEvaluationsRouteWithChildren
  '/research/ideas': typeof ResearchIdeasRouteWithChildren
  '/research/projects': typeof ResearchProjectsRouteWithChildren
  '/research/reports': typeof ResearchReportsRoute
  '/research/screenings': typeof ResearchScreeningsRouteWithChildren
  '/research/transfers': typeof ResearchTransfersRouteWithChildren
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/sub-cities/$id': typeof SubCitiesIdRouteWithChildren
  '/sub-cities/create': typeof SubCitiesCreateRoute
  '/users/create': typeof UsersCreateRoute
  '/vendors/create': typeof VendorsCreateRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/registry/': typeof RegistryIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/sub-cities/': typeof SubCitiesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/registry/$id/edit': typeof RegistryIdEditRoute
  '/requests/$id/edit': typeof RequestsIdEditRoute
  '/research/ideas/$id': typeof ResearchIdeasIdRouteWithChildren
  '/research/ideas/create': typeof ResearchIdeasCreateRoute
  '/research/projects/$id': typeof ResearchProjectsIdRoute
  '/sub-cities/$id/edit': typeof SubCitiesIdEditRoute
  '/users/$id/edit': typeof UsersIdEditRoute
  '/sub-cities/$id/': typeof SubCitiesIdIndexRoute
  '/research/evaluations/create/$projectId': typeof ResearchEvaluationsCreateProjectIdRoute
  '/research/ideas/$id/edit': typeof ResearchIdeasIdEditRoute
  '/research/projects/create/$ideaId': typeof ResearchProjectsCreateIdeaIdRoute
  '/research/screenings/create/$ideaId': typeof ResearchScreeningsCreateIdeaIdRoute
  '/research/transfers/create/$projectId': typeof ResearchTransfersCreateProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/cybersecurity'
    | '/dashboard'
    | '/duplication'
    | '/feasibility'
    | '/forgot-password'
    | '/institution-register'
    | '/login'
    | '/notifications'
    | '/registry'
    | '/reports'
    | '/requests'
    | '/settings'
    | '/sub-cities'
    | '/surveys'
    | '/users'
    | '/vendors'
    | '/workflows'
    | '/registry/create'
    | '/requests/create'
    | '/research/evaluations'
    | '/research/ideas'
    | '/research/projects'
    | '/research/reports'
    | '/research/screenings'
    | '/research/transfers'
    | '/services/$serviceSlug'
    | '/sub-cities/$id'
    | '/sub-cities/create'
    | '/users/create'
    | '/vendors/create'
    | '/notifications/'
    | '/profile/'
    | '/registry/'
    | '/requests/'
    | '/sub-cities/'
    | '/users/'
    | '/vendors/'
    | '/registry/$id/edit'
    | '/requests/$id/edit'
    | '/research/ideas/$id'
    | '/research/ideas/create'
    | '/research/projects/$id'
    | '/sub-cities/$id/edit'
    | '/users/$id/edit'
    | '/sub-cities/$id/'
    | '/research/evaluations/create/$projectId'
    | '/research/ideas/$id/edit'
    | '/research/projects/create/$ideaId'
    | '/research/screenings/create/$ideaId'
    | '/research/transfers/create/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/cybersecurity'
    | '/dashboard'
    | '/duplication'
    | '/feasibility'
    | '/forgot-password'
    | '/institution-register'
    | '/login'
    | '/reports'
    | '/settings'
    | '/surveys'
    | '/workflows'
    | '/registry/create'
    | '/requests/create'
    | '/research/evaluations'
    | '/research/ideas'
    | '/research/projects'
    | '/research/reports'
    | '/research/screenings'
    | '/research/transfers'
    | '/services/$serviceSlug'
    | '/sub-cities/create'
    | '/users/create'
    | '/vendors/create'
    | '/notifications'
    | '/profile'
    | '/registry'
    | '/requests'
    | '/sub-cities'
    | '/users'
    | '/vendors'
    | '/registry/$id/edit'
    | '/requests/$id/edit'
    | '/research/ideas/$id'
    | '/research/ideas/create'
    | '/research/projects/$id'
    | '/sub-cities/$id/edit'
    | '/users/$id/edit'
    | '/sub-cities/$id'
    | '/research/evaluations/create/$projectId'
    | '/research/ideas/$id/edit'
    | '/research/projects/create/$ideaId'
    | '/research/screenings/create/$ideaId'
    | '/research/transfers/create/$projectId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/cybersecurity'
    | '/dashboard'
    | '/duplication'
    | '/feasibility'
    | '/forgot-password'
    | '/institution-register'
    | '/login'
    | '/notifications'
    | '/registry'
    | '/reports'
    | '/requests'
    | '/settings'
    | '/sub-cities'
    | '/surveys'
    | '/users'
    | '/vendors'
    | '/workflows'
    | '/registry/create'
    | '/requests/create'
    | '/research/evaluations'
    | '/research/ideas'
    | '/research/projects'
    | '/research/reports'
    | '/research/screenings'
    | '/research/transfers'
    | '/services/$serviceSlug'
    | '/sub-cities/$id'
    | '/sub-cities/create'
    | '/users/create'
    | '/vendors/create'
    | '/notifications/'
    | '/profile/'
    | '/registry/'
    | '/requests/'
    | '/sub-cities/'
    | '/users/'
    | '/vendors/'
    | '/registry/$id/edit'
    | '/requests/$id/edit'
    | '/research/ideas/$id'
    | '/research/ideas/create'
    | '/research/projects/$id'
    | '/sub-cities/$id/edit'
    | '/users/$id/edit'
    | '/sub-cities/$id/'
    | '/research/evaluations/create/$projectId'
    | '/research/ideas/$id/edit'
    | '/research/projects/create/$ideaId'
    | '/research/screenings/create/$ideaId'
    | '/research/transfers/create/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CybersecurityRoute: typeof CybersecurityRoute
  DashboardRoute: typeof DashboardRoute
  DuplicationRoute: typeof DuplicationRoute
  FeasibilityRoute: typeof FeasibilityRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InstitutionRegisterRoute: typeof InstitutionRegisterRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRouteWithChildren
  RegistryRoute: typeof RegistryRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  RequestsRoute: typeof RequestsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SubCitiesRoute: typeof SubCitiesRouteWithChildren
  SurveysRoute: typeof SurveysRoute
  UsersRoute: typeof UsersRouteWithChildren
  VendorsRoute: typeof VendorsRouteWithChildren
  WorkflowsRoute: typeof WorkflowsRoute
  ResearchEvaluationsRoute: typeof ResearchEvaluationsRouteWithChildren
  ResearchIdeasRoute: typeof ResearchIdeasRouteWithChildren
  ResearchProjectsRoute: typeof ResearchProjectsRouteWithChildren
  ResearchReportsRoute: typeof ResearchReportsRoute
  ResearchScreeningsRoute: typeof ResearchScreeningsRouteWithChildren
  ResearchTransfersRoute: typeof ResearchTransfersRouteWithChildren
  ServicesServiceSlugRoute: typeof ServicesServiceSlugRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-cities': {
      id: '/sub-cities'
      path: '/sub-cities'
      fullPath: '/sub-cities'
      preLoaderRoute: typeof SubCitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution-register': {
      id: '/institution-register'
      path: '/institution-register'
      fullPath: '/institution-register'
      preLoaderRoute: typeof InstitutionRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feasibility': {
      id: '/feasibility'
      path: '/feasibility'
      fullPath: '/feasibility'
      preLoaderRoute: typeof FeasibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplication': {
      id: '/duplication'
      path: '/duplication'
      fullPath: '/duplication'
      preLoaderRoute: typeof DuplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurity': {
      id: '/cybersecurity'
      path: '/cybersecurity'
      fullPath: '/cybersecurity'
      preLoaderRoute: typeof CybersecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/sub-cities/': {
      id: '/sub-cities/'
      path: '/'
      fullPath: '/sub-cities/'
      preLoaderRoute: typeof SubCitiesIndexRouteImport
      parentRoute: typeof SubCitiesRoute
    }
    '/requests/': {
      id: '/requests/'
      path: '/'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/registry/': {
      id: '/registry/'
      path: '/'
      fullPath: '/registry/'
      preLoaderRoute: typeof RegistryIndexRouteImport
      parentRoute: typeof RegistryRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/vendors/create': {
      id: '/vendors/create'
      path: '/create'
      fullPath: '/vendors/create'
      preLoaderRoute: typeof VendorsCreateRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/users/create': {
      id: '/users/create'
      path: '/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof UsersCreateRouteImport
      parentRoute: typeof UsersRoute
    }
    '/sub-cities/create': {
      id: '/sub-cities/create'
      path: '/create'
      fullPath: '/sub-cities/create'
      preLoaderRoute: typeof SubCitiesCreateRouteImport
      parentRoute: typeof SubCitiesRoute
    }
    '/sub-cities/$id': {
      id: '/sub-cities/$id'
      path: '/$id'
      fullPath: '/sub-cities/$id'
      preLoaderRoute: typeof SubCitiesIdRouteImport
      parentRoute: typeof SubCitiesRoute
    }
    '/services/$serviceSlug': {
      id: '/services/$serviceSlug'
      path: '/services/$serviceSlug'
      fullPath: '/services/$serviceSlug'
      preLoaderRoute: typeof ServicesServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/transfers': {
      id: '/research/transfers'
      path: '/research/transfers'
      fullPath: '/research/transfers'
      preLoaderRoute: typeof ResearchTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/screenings': {
      id: '/research/screenings'
      path: '/research/screenings'
      fullPath: '/research/screenings'
      preLoaderRoute: typeof ResearchScreeningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/reports': {
      id: '/research/reports'
      path: '/research/reports'
      fullPath: '/research/reports'
      preLoaderRoute: typeof ResearchReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/projects': {
      id: '/research/projects'
      path: '/research/projects'
      fullPath: '/research/projects'
      preLoaderRoute: typeof ResearchProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/ideas': {
      id: '/research/ideas'
      path: '/research/ideas'
      fullPath: '/research/ideas'
      preLoaderRoute: typeof ResearchIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/evaluations': {
      id: '/research/evaluations'
      path: '/research/evaluations'
      fullPath: '/research/evaluations'
      preLoaderRoute: typeof ResearchEvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/create': {
      id: '/requests/create'
      path: '/create'
      fullPath: '/requests/create'
      preLoaderRoute: typeof RequestsCreateRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/registry/create': {
      id: '/registry/create'
      path: '/create'
      fullPath: '/registry/create'
      preLoaderRoute: typeof RegistryCreateRouteImport
      parentRoute: typeof RegistryRoute
    }
    '/sub-cities/$id/': {
      id: '/sub-cities/$id/'
      path: '/'
      fullPath: '/sub-cities/$id/'
      preLoaderRoute: typeof SubCitiesIdIndexRouteImport
      parentRoute: typeof SubCitiesIdRoute
    }
    '/users/$id/edit': {
      id: '/users/$id/edit'
      path: '/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof UsersIdEditRouteImport
      parentRoute: typeof UsersRoute
    }
    '/sub-cities/$id/edit': {
      id: '/sub-cities/$id/edit'
      path: '/edit'
      fullPath: '/sub-cities/$id/edit'
      preLoaderRoute: typeof SubCitiesIdEditRouteImport
      parentRoute: typeof SubCitiesIdRoute
    }
    '/research/projects/$id': {
      id: '/research/projects/$id'
      path: '/$id'
      fullPath: '/research/projects/$id'
      preLoaderRoute: typeof ResearchProjectsIdRouteImport
      parentRoute: typeof ResearchProjectsRoute
    }
    '/research/ideas/create': {
      id: '/research/ideas/create'
      path: '/create'
      fullPath: '/research/ideas/create'
      preLoaderRoute: typeof ResearchIdeasCreateRouteImport
      parentRoute: typeof ResearchIdeasRoute
    }
    '/research/ideas/$id': {
      id: '/research/ideas/$id'
      path: '/$id'
      fullPath: '/research/ideas/$id'
      preLoaderRoute: typeof ResearchIdeasIdRouteImport
      parentRoute: typeof ResearchIdeasRoute
    }
    '/requests/$id/edit': {
      id: '/requests/$id/edit'
      path: '/$id/edit'
      fullPath: '/requests/$id/edit'
      preLoaderRoute: typeof RequestsIdEditRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/registry/$id/edit': {
      id: '/registry/$id/edit'
      path: '/$id/edit'
      fullPath: '/registry/$id/edit'
      preLoaderRoute: typeof RegistryIdEditRouteImport
      parentRoute: typeof RegistryRoute
    }
    '/research/transfers/create/$projectId': {
      id: '/research/transfers/create/$projectId'
      path: '/create/$projectId'
      fullPath: '/research/transfers/create/$projectId'
      preLoaderRoute: typeof ResearchTransfersCreateProjectIdRouteImport
      parentRoute: typeof ResearchTransfersRoute
    }
    '/research/screenings/create/$ideaId': {
      id: '/research/screenings/create/$ideaId'
      path: '/create/$ideaId'
      fullPath: '/research/screenings/create/$ideaId'
      preLoaderRoute: typeof ResearchScreeningsCreateIdeaIdRouteImport
      parentRoute: typeof ResearchScreeningsRoute
    }
    '/research/projects/create/$ideaId': {
      id: '/research/projects/create/$ideaId'
      path: '/create/$ideaId'
      fullPath: '/research/projects/create/$ideaId'
      preLoaderRoute: typeof ResearchProjectsCreateIdeaIdRouteImport
      parentRoute: typeof ResearchProjectsRoute
    }
    '/research/ideas/$id/edit': {
      id: '/research/ideas/$id/edit'
      path: '/edit'
      fullPath: '/research/ideas/$id/edit'
      preLoaderRoute: typeof ResearchIdeasIdEditRouteImport
      parentRoute: typeof ResearchIdeasIdRoute
    }
    '/research/evaluations/create/$projectId': {
      id: '/research/evaluations/create/$projectId'
      path: '/create/$projectId'
      fullPath: '/research/evaluations/create/$projectId'
      preLoaderRoute: typeof ResearchEvaluationsCreateProjectIdRouteImport
      parentRoute: typeof ResearchEvaluationsRoute
    }
  }
}

interface NotificationsRouteChildren {
  NotificationsIndexRoute: typeof NotificationsIndexRoute
}

const NotificationsRouteChildren: NotificationsRouteChildren = {
  NotificationsIndexRoute: NotificationsIndexRoute,
}

const NotificationsRouteWithChildren = NotificationsRoute._addFileChildren(
  NotificationsRouteChildren,
)

interface RegistryRouteChildren {
  RegistryCreateRoute: typeof RegistryCreateRoute
  RegistryIndexRoute: typeof RegistryIndexRoute
  RegistryIdEditRoute: typeof RegistryIdEditRoute
}

const RegistryRouteChildren: RegistryRouteChildren = {
  RegistryCreateRoute: RegistryCreateRoute,
  RegistryIndexRoute: RegistryIndexRoute,
  RegistryIdEditRoute: RegistryIdEditRoute,
}

const RegistryRouteWithChildren = RegistryRoute._addFileChildren(
  RegistryRouteChildren,
)

interface RequestsRouteChildren {
  RequestsCreateRoute: typeof RequestsCreateRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  RequestsIdEditRoute: typeof RequestsIdEditRoute
}

const RequestsRouteChildren: RequestsRouteChildren = {
  RequestsCreateRoute: RequestsCreateRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  RequestsIdEditRoute: RequestsIdEditRoute,
}

const RequestsRouteWithChildren = RequestsRoute._addFileChildren(
  RequestsRouteChildren,
)

interface SubCitiesIdRouteChildren {
  SubCitiesIdEditRoute: typeof SubCitiesIdEditRoute
  SubCitiesIdIndexRoute: typeof SubCitiesIdIndexRoute
}

const SubCitiesIdRouteChildren: SubCitiesIdRouteChildren = {
  SubCitiesIdEditRoute: SubCitiesIdEditRoute,
  SubCitiesIdIndexRoute: SubCitiesIdIndexRoute,
}

const SubCitiesIdRouteWithChildren = SubCitiesIdRoute._addFileChildren(
  SubCitiesIdRouteChildren,
)

interface SubCitiesRouteChildren {
  SubCitiesIdRoute: typeof SubCitiesIdRouteWithChildren
  SubCitiesCreateRoute: typeof SubCitiesCreateRoute
  SubCitiesIndexRoute: typeof SubCitiesIndexRoute
}

const SubCitiesRouteChildren: SubCitiesRouteChildren = {
  SubCitiesIdRoute: SubCitiesIdRouteWithChildren,
  SubCitiesCreateRoute: SubCitiesCreateRoute,
  SubCitiesIndexRoute: SubCitiesIndexRoute,
}

const SubCitiesRouteWithChildren = SubCitiesRoute._addFileChildren(
  SubCitiesRouteChildren,
)

interface UsersRouteChildren {
  UsersCreateRoute: typeof UsersCreateRoute
  UsersIndexRoute: typeof UsersIndexRoute
  UsersIdEditRoute: typeof UsersIdEditRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersCreateRoute: UsersCreateRoute,
  UsersIndexRoute: UsersIndexRoute,
  UsersIdEditRoute: UsersIdEditRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface VendorsRouteChildren {
  VendorsCreateRoute: typeof VendorsCreateRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

const VendorsRouteChildren: VendorsRouteChildren = {
  VendorsCreateRoute: VendorsCreateRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}

const VendorsRouteWithChildren =
  VendorsRoute._addFileChildren(VendorsRouteChildren)

interface ResearchEvaluationsRouteChildren {
  ResearchEvaluationsCreateProjectIdRoute: typeof ResearchEvaluationsCreateProjectIdRoute
}

const ResearchEvaluationsRouteChildren: ResearchEvaluationsRouteChildren = {
  ResearchEvaluationsCreateProjectIdRoute:
    ResearchEvaluationsCreateProjectIdRoute,
}

const ResearchEvaluationsRouteWithChildren =
  ResearchEvaluationsRoute._addFileChildren(ResearchEvaluationsRouteChildren)

interface ResearchIdeasIdRouteChildren {
  ResearchIdeasIdEditRoute: typeof ResearchIdeasIdEditRoute
}

const ResearchIdeasIdRouteChildren: ResearchIdeasIdRouteChildren = {
  ResearchIdeasIdEditRoute: ResearchIdeasIdEditRoute,
}

const ResearchIdeasIdRouteWithChildren = ResearchIdeasIdRoute._addFileChildren(
  ResearchIdeasIdRouteChildren,
)

interface ResearchIdeasRouteChildren {
  ResearchIdeasIdRoute: typeof ResearchIdeasIdRouteWithChildren
  ResearchIdeasCreateRoute: typeof ResearchIdeasCreateRoute
}

const ResearchIdeasRouteChildren: ResearchIdeasRouteChildren = {
  ResearchIdeasIdRoute: ResearchIdeasIdRouteWithChildren,
  ResearchIdeasCreateRoute: ResearchIdeasCreateRoute,
}

const ResearchIdeasRouteWithChildren = ResearchIdeasRoute._addFileChildren(
  ResearchIdeasRouteChildren,
)

interface ResearchProjectsRouteChildren {
  ResearchProjectsIdRoute: typeof ResearchProjectsIdRoute
  ResearchProjectsCreateIdeaIdRoute: typeof ResearchProjectsCreateIdeaIdRoute
}

const ResearchProjectsRouteChildren: ResearchProjectsRouteChildren = {
  ResearchProjectsIdRoute: ResearchProjectsIdRoute,
  ResearchProjectsCreateIdeaIdRoute: ResearchProjectsCreateIdeaIdRoute,
}

const ResearchProjectsRouteWithChildren =
  ResearchProjectsRoute._addFileChildren(ResearchProjectsRouteChildren)

interface ResearchScreeningsRouteChildren {
  ResearchScreeningsCreateIdeaIdRoute: typeof ResearchScreeningsCreateIdeaIdRoute
}

const ResearchScreeningsRouteChildren: ResearchScreeningsRouteChildren = {
  ResearchScreeningsCreateIdeaIdRoute: ResearchScreeningsCreateIdeaIdRoute,
}

const ResearchScreeningsRouteWithChildren =
  ResearchScreeningsRoute._addFileChildren(ResearchScreeningsRouteChildren)

interface ResearchTransfersRouteChildren {
  ResearchTransfersCreateProjectIdRoute: typeof ResearchTransfersCreateProjectIdRoute
}

const ResearchTransfersRouteChildren: ResearchTransfersRouteChildren = {
  ResearchTransfersCreateProjectIdRoute: ResearchTransfersCreateProjectIdRoute,
}

const ResearchTransfersRouteWithChildren =
  ResearchTransfersRoute._addFileChildren(ResearchTransfersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CybersecurityRoute: CybersecurityRoute,
  DashboardRoute: DashboardRoute,
  DuplicationRoute: DuplicationRoute,
  FeasibilityRoute: FeasibilityRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InstitutionRegisterRoute: InstitutionRegisterRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRouteWithChildren,
  RegistryRoute: RegistryRouteWithChildren,
  ReportsRoute: ReportsRoute,
  RequestsRoute: RequestsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SubCitiesRoute: SubCitiesRouteWithChildren,
  SurveysRoute: SurveysRoute,
  UsersRoute: UsersRouteWithChildren,
  VendorsRoute: VendorsRouteWithChildren,
  WorkflowsRoute: WorkflowsRoute,
  ResearchEvaluationsRoute: ResearchEvaluationsRouteWithChildren,
  ResearchIdeasRoute: ResearchIdeasRouteWithChildren,
  ResearchProjectsRoute: ResearchProjectsRouteWithChildren,
  ResearchReportsRoute: ResearchReportsRoute,
  ResearchScreeningsRoute: ResearchScreeningsRouteWithChildren,
  ResearchTransfersRoute: ResearchTransfersRouteWithChildren,
  ServicesServiceSlugRoute: ServicesServiceSlugRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
