/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServiceRequestsRouteImport } from './routes/service-requests'
import { Route as SecurityReviewRouteImport } from './routes/security-review'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as RbacRouteImport } from './routes/rbac'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstitutionRegisterRouteImport } from './routes/institution-register'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeasibilityRouteImport } from './routes/feasibility'
import { Route as DuplicationRouteImport } from './routes/duplication'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CybersecurityRouteImport } from './routes/cybersecurity'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as TicketsIndexRouteImport } from './routes/tickets.index'
import { Route as ServiceRequestsIndexRouteImport } from './routes/service-requests.index'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as RegistryIndexRouteImport } from './routes/registry.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VendorsCreateRouteImport } from './routes/vendors.create'
import { Route as UsersCreateRouteImport } from './routes/users.create'
import { Route as TicketsCreateRouteImport } from './routes/tickets.create'
import { Route as TicketsIdRouteImport } from './routes/tickets.$id'
import { Route as ServicesServiceSlugRouteImport } from './routes/services.$serviceSlug'
import { Route as ServiceRequestsIdRouteImport } from './routes/service-requests.$id'
import { Route as ResearchTransfersRouteImport } from './routes/research.transfers'
import { Route as ResearchTeamRouteImport } from './routes/research.team'
import { Route as ResearchScreeningsRouteImport } from './routes/research.screenings'
import { Route as ResearchReportsRouteImport } from './routes/research.reports'
import { Route as ResearchProjectsRouteImport } from './routes/research.projects'
import { Route as ResearchIdeasRouteImport } from './routes/research.ideas'
import { Route as ResearchEvaluationsRouteImport } from './routes/research.evaluations'
import { Route as ResearchAssignmentsRouteImport } from './routes/research.assignments'
import { Route as ResearchAssignedRouteImport } from './routes/research.assigned'
import { Route as RequestsCreateRouteImport } from './routes/requests.create'
import { Route as RequestsAssignedRouteImport } from './routes/requests.assigned'
import { Route as RegistryCreateRouteImport } from './routes/registry.create'
import { Route as DocumentsIdRouteImport } from './routes/documents.$id'
import { Route as DashboardTechnologyTransferRouteImport } from './routes/dashboard.technology-transfer'
import { Route as DashboardSubcityRouteImport } from './routes/dashboard.subcity'
import { Route as DashboardResearchRouteImport } from './routes/dashboard.research'
import { Route as DashboardNoAccessRouteImport } from './routes/dashboard.no-access'
import { Route as DashboardMainRouteImport } from './routes/dashboard.main'
import { Route as DashboardLicensingRouteImport } from './routes/dashboard.licensing'
import { Route as DashboardInstitutionRouteImport } from './routes/dashboard.institution'
import { Route as DashboardExecutiveRouteImport } from './routes/dashboard.executive'
import { Route as DashboardBureauHeadRouteImport } from './routes/dashboard.bureau-head'
import { Route as DashboardAuditorRouteImport } from './routes/dashboard.auditor'
import { Route as ServiceRequestsIdIndexRouteImport } from './routes/service-requests.$id.index'
import { Route as ResearchIdeasIndexRouteImport } from './routes/research.ideas.index'
import { Route as UsersIdEditRouteImport } from './routes/users.$id.edit'
import { Route as ServiceRequestsIdWorkspaceRouteImport } from './routes/service-requests.$id.workspace'
import { Route as ResearchTeamLeaderReviewsRouteImport } from './routes/research.team-leader.reviews'
import { Route as ResearchTeamLeaderDashboardRouteImport } from './routes/research.team-leader.dashboard'
import { Route as ResearchProjectsIdRouteImport } from './routes/research.projects.$id'
import { Route as ResearchOfficerSubmissionsRouteImport } from './routes/research.officer.submissions'
import { Route as ResearchOfficerStagesRouteImport } from './routes/research.officer.stages'
import { Route as ResearchOfficerDocumentsRouteImport } from './routes/research.officer.documents'
import { Route as ResearchOfficerDashboardRouteImport } from './routes/research.officer.dashboard'
import { Route as ResearchOfficerAssignmentsRouteImport } from './routes/research.officer.assignments'
import { Route as ResearchOfficerAssessmentsRouteImport } from './routes/research.officer.assessments'
import { Route as ResearchIdeasTeamLeaderRouteImport } from './routes/research.ideas.team-leader'
import { Route as ResearchIdeasDirectorRouteImport } from './routes/research.ideas.director'
import { Route as ResearchIdeasCreateRouteImport } from './routes/research.ideas.create'
import { Route as ResearchIdeasIdRouteImport } from './routes/research.ideas.$id'
import { Route as RequestsIdEditRouteImport } from './routes/requests.$id.edit'
import { Route as RegistryIdEditRouteImport } from './routes/registry.$id.edit'
import { Route as ResearchIdeasIdIndexRouteImport } from './routes/research.ideas.$id.index'
import { Route as ResearchTransfersCreateProjectIdRouteImport } from './routes/research.transfers.create.$projectId'
import { Route as ResearchScreeningsCreateIdeaIdRouteImport } from './routes/research.screenings.create.$ideaId'
import { Route as ResearchProjectsCreateIdeaIdRouteImport } from './routes/research.projects.create.$ideaId'
import { Route as ResearchIdeasIdWorkspaceRouteImport } from './routes/research.ideas.$id.workspace'
import { Route as ResearchIdeasIdEditRouteImport } from './routes/research.ideas.$id.edit'
import { Route as ResearchIdeasIdDirectorRouteImport } from './routes/research.ideas.$id.director'
import { Route as ResearchEvaluationsCreateProjectIdRouteImport } from './routes/research.evaluations.create.$projectId'
import { Route as ResearchIdeasIdWorkflowProgressIdWorkRouteImport } from './routes/research.ideas.$id.workflow.$progressId.work'
import { Route as ResearchIdeasIdWorkflowProgressIdReviewRouteImport } from './routes/research.ideas.$id.workflow.$progressId.review'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRequestsRoute = ServiceRequestsRouteImport.update({
  id: '/service-requests',
  path: '/service-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityReviewRoute = SecurityReviewRouteImport.update({
  id: '/security-review',
  path: '/security-review',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const RbacRoute = RbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionRegisterRoute = InstitutionRegisterRouteImport.update({
  id: '/institution-register',
  path: '/institution-register',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeasibilityRoute = FeasibilityRouteImport.update({
  id: '/feasibility',
  path: '/feasibility',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicationRoute = DuplicationRouteImport.update({
  id: '/duplication',
  path: '/duplication',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CybersecurityRoute = CybersecurityRouteImport.update({
  id: '/cybersecurity',
  path: '/cybersecurity',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorsRoute,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TicketsRoute,
} as any)
const ServiceRequestsIndexRoute = ServiceRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceRequestsRoute,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequestsRoute,
} as any)
const RegistryIndexRoute = RegistryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegistryRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotificationsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VendorsCreateRoute = VendorsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => VendorsRoute,
} as any)
const UsersCreateRoute = UsersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => UsersRoute,
} as any)
const TicketsCreateRoute = TicketsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TicketsRoute,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TicketsRoute,
} as any)
const ServicesServiceSlugRoute = ServicesServiceSlugRouteImport.update({
  id: '/services/$serviceSlug',
  path: '/services/$serviceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRequestsIdRoute = ServiceRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ServiceRequestsRoute,
} as any)
const ResearchTransfersRoute = ResearchTransfersRouteImport.update({
  id: '/research/transfers',
  path: '/research/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchTeamRoute = ResearchTeamRouteImport.update({
  id: '/research/team',
  path: '/research/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchScreeningsRoute = ResearchScreeningsRouteImport.update({
  id: '/research/screenings',
  path: '/research/screenings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchReportsRoute = ResearchReportsRouteImport.update({
  id: '/research/reports',
  path: '/research/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchProjectsRoute = ResearchProjectsRouteImport.update({
  id: '/research/projects',
  path: '/research/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIdeasRoute = ResearchIdeasRouteImport.update({
  id: '/research/ideas',
  path: '/research/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchEvaluationsRoute = ResearchEvaluationsRouteImport.update({
  id: '/research/evaluations',
  path: '/research/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchAssignmentsRoute = ResearchAssignmentsRouteImport.update({
  id: '/research/assignments',
  path: '/research/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchAssignedRoute = ResearchAssignedRouteImport.update({
  id: '/research/assigned',
  path: '/research/assigned',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsCreateRoute = RequestsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => RequestsRoute,
} as any)
const RequestsAssignedRoute = RequestsAssignedRouteImport.update({
  id: '/assigned',
  path: '/assigned',
  getParentRoute: () => RequestsRoute,
} as any)
const RegistryCreateRoute = RegistryCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => RegistryRoute,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTechnologyTransferRoute =
  DashboardTechnologyTransferRouteImport.update({
    id: '/technology-transfer',
    path: '/technology-transfer',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSubcityRoute = DashboardSubcityRouteImport.update({
  id: '/subcity',
  path: '/subcity',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResearchRoute = DashboardResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNoAccessRoute = DashboardNoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMainRoute = DashboardMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLicensingRoute = DashboardLicensingRouteImport.update({
  id: '/licensing',
  path: '/licensing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInstitutionRoute = DashboardInstitutionRouteImport.update({
  id: '/institution',
  path: '/institution',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExecutiveRoute = DashboardExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBureauHeadRoute = DashboardBureauHeadRouteImport.update({
  id: '/bureau-head',
  path: '/bureau-head',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditorRoute = DashboardAuditorRouteImport.update({
  id: '/auditor',
  path: '/auditor',
  getParentRoute: () => DashboardRoute,
} as any)
const ServiceRequestsIdIndexRoute = ServiceRequestsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceRequestsIdRoute,
} as any)
const ResearchIdeasIndexRoute = ResearchIdeasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResearchIdeasRoute,
} as any)
const UsersIdEditRoute = UsersIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => UsersRoute,
} as any)
const ServiceRequestsIdWorkspaceRoute =
  ServiceRequestsIdWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => ServiceRequestsIdRoute,
  } as any)
const ResearchTeamLeaderReviewsRoute =
  ResearchTeamLeaderReviewsRouteImport.update({
    id: '/research/team-leader/reviews',
    path: '/research/team-leader/reviews',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResearchTeamLeaderDashboardRoute =
  ResearchTeamLeaderDashboardRouteImport.update({
    id: '/research/team-leader/dashboard',
    path: '/research/team-leader/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResearchProjectsIdRoute = ResearchProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResearchProjectsRoute,
} as any)
const ResearchOfficerSubmissionsRoute =
  ResearchOfficerSubmissionsRouteImport.update({
    id: '/research/officer/submissions',
    path: '/research/officer/submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResearchOfficerStagesRoute = ResearchOfficerStagesRouteImport.update({
  id: '/research/officer/stages',
  path: '/research/officer/stages',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchOfficerDocumentsRoute =
  ResearchOfficerDocumentsRouteImport.update({
    id: '/research/officer/documents',
    path: '/research/officer/documents',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResearchOfficerDashboardRoute =
  ResearchOfficerDashboardRouteImport.update({
    id: '/research/officer/dashboard',
    path: '/research/officer/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResearchOfficerAssignmentsRoute =
  ResearchOfficerAssignmentsRouteImport.update({
    id: '/research/officer/assignments',
    path: '/research/officer/assignments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResearchOfficerAssessmentsRoute =
  ResearchOfficerAssessmentsRouteImport.update({
    id: '/research/officer/assessments',
    path: '/research/officer/assessments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResearchIdeasTeamLeaderRoute = ResearchIdeasTeamLeaderRouteImport.update({
  id: '/team-leader',
  path: '/team-leader',
  getParentRoute: () => ResearchIdeasRoute,
} as any)
const ResearchIdeasDirectorRoute = ResearchIdeasDirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => ResearchIdeasRoute,
} as any)
const ResearchIdeasCreateRoute = ResearchIdeasCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ResearchIdeasRoute,
} as any)
const ResearchIdeasIdRoute = ResearchIdeasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResearchIdeasRoute,
} as any)
const RequestsIdEditRoute = RequestsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => RequestsRoute,
} as any)
const RegistryIdEditRoute = RegistryIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => RegistryRoute,
} as any)
const ResearchIdeasIdIndexRoute = ResearchIdeasIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResearchIdeasIdRoute,
} as any)
const ResearchTransfersCreateProjectIdRoute =
  ResearchTransfersCreateProjectIdRouteImport.update({
    id: '/create/$projectId',
    path: '/create/$projectId',
    getParentRoute: () => ResearchTransfersRoute,
  } as any)
const ResearchScreeningsCreateIdeaIdRoute =
  ResearchScreeningsCreateIdeaIdRouteImport.update({
    id: '/create/$ideaId',
    path: '/create/$ideaId',
    getParentRoute: () => ResearchScreeningsRoute,
  } as any)
const ResearchProjectsCreateIdeaIdRoute =
  ResearchProjectsCreateIdeaIdRouteImport.update({
    id: '/create/$ideaId',
    path: '/create/$ideaId',
    getParentRoute: () => ResearchProjectsRoute,
  } as any)
const ResearchIdeasIdWorkspaceRoute =
  ResearchIdeasIdWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => ResearchIdeasIdRoute,
  } as any)
const ResearchIdeasIdEditRoute = ResearchIdeasIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ResearchIdeasIdRoute,
} as any)
const ResearchIdeasIdDirectorRoute = ResearchIdeasIdDirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => ResearchIdeasIdRoute,
} as any)
const ResearchEvaluationsCreateProjectIdRoute =
  ResearchEvaluationsCreateProjectIdRouteImport.update({
    id: '/create/$projectId',
    path: '/create/$projectId',
    getParentRoute: () => ResearchEvaluationsRoute,
  } as any)
const ResearchIdeasIdWorkflowProgressIdWorkRoute =
  ResearchIdeasIdWorkflowProgressIdWorkRouteImport.update({
    id: '/workflow/$progressId/work',
    path: '/workflow/$progressId/work',
    getParentRoute: () => ResearchIdeasIdRoute,
  } as any)
const ResearchIdeasIdWorkflowProgressIdReviewRoute =
  ResearchIdeasIdWorkflowProgressIdReviewRouteImport.update({
    id: '/workflow/$progressId/review',
    path: '/workflow/$progressId/review',
    getParentRoute: () => ResearchIdeasIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/cloud': typeof CloudRoute
  '/cybersecurity': typeof CybersecurityRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/development': typeof DevelopmentRoute
  '/duplication': typeof DuplicationRoute
  '/feasibility': typeof FeasibilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/infrastructure': typeof InfrastructureRoute
  '/institution-register': typeof InstitutionRegisterRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/permissions': typeof PermissionsRoute
  '/projects': typeof ProjectsRoute
  '/quality': typeof QualityRoute
  '/rbac': typeof RbacRoute
  '/registry': typeof RegistryRouteWithChildren
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRouteWithChildren
  '/security-review': typeof SecurityReviewRoute
  '/service-requests': typeof ServiceRequestsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/surveys': typeof SurveysRoute
  '/tasks': typeof TasksRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/training': typeof TrainingRoute
  '/users': typeof UsersRouteWithChildren
  '/vendors': typeof VendorsRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/dashboard/auditor': typeof DashboardAuditorRoute
  '/dashboard/bureau-head': typeof DashboardBureauHeadRoute
  '/dashboard/executive': typeof DashboardExecutiveRoute
  '/dashboard/institution': typeof DashboardInstitutionRoute
  '/dashboard/licensing': typeof DashboardLicensingRoute
  '/dashboard/main': typeof DashboardMainRoute
  '/dashboard/no-access': typeof DashboardNoAccessRoute
  '/dashboard/research': typeof DashboardResearchRoute
  '/dashboard/subcity': typeof DashboardSubcityRoute
  '/dashboard/technology-transfer': typeof DashboardTechnologyTransferRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/registry/create': typeof RegistryCreateRoute
  '/requests/assigned': typeof RequestsAssignedRoute
  '/requests/create': typeof RequestsCreateRoute
  '/research/assigned': typeof ResearchAssignedRoute
  '/research/assignments': typeof ResearchAssignmentsRoute
  '/research/evaluations': typeof ResearchEvaluationsRouteWithChildren
  '/research/ideas': typeof ResearchIdeasRouteWithChildren
  '/research/projects': typeof ResearchProjectsRouteWithChildren
  '/research/reports': typeof ResearchReportsRoute
  '/research/screenings': typeof ResearchScreeningsRouteWithChildren
  '/research/team': typeof ResearchTeamRoute
  '/research/transfers': typeof ResearchTransfersRouteWithChildren
  '/service-requests/$id': typeof ServiceRequestsIdRouteWithChildren
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tickets/create': typeof TicketsCreateRoute
  '/users/create': typeof UsersCreateRoute
  '/vendors/create': typeof VendorsCreateRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/registry/': typeof RegistryIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/service-requests/': typeof ServiceRequestsIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/registry/$id/edit': typeof RegistryIdEditRoute
  '/requests/$id/edit': typeof RequestsIdEditRoute
  '/research/ideas/$id': typeof ResearchIdeasIdRouteWithChildren
  '/research/ideas/create': typeof ResearchIdeasCreateRoute
  '/research/ideas/director': typeof ResearchIdeasDirectorRoute
  '/research/ideas/team-leader': typeof ResearchIdeasTeamLeaderRoute
  '/research/officer/assessments': typeof ResearchOfficerAssessmentsRoute
  '/research/officer/assignments': typeof ResearchOfficerAssignmentsRoute
  '/research/officer/dashboard': typeof ResearchOfficerDashboardRoute
  '/research/officer/documents': typeof ResearchOfficerDocumentsRoute
  '/research/officer/stages': typeof ResearchOfficerStagesRoute
  '/research/officer/submissions': typeof ResearchOfficerSubmissionsRoute
  '/research/projects/$id': typeof ResearchProjectsIdRoute
  '/research/team-leader/dashboard': typeof ResearchTeamLeaderDashboardRoute
  '/research/team-leader/reviews': typeof ResearchTeamLeaderReviewsRoute
  '/service-requests/$id/workspace': typeof ServiceRequestsIdWorkspaceRoute
  '/users/$id/edit': typeof UsersIdEditRoute
  '/research/ideas/': typeof ResearchIdeasIndexRoute
  '/service-requests/$id/': typeof ServiceRequestsIdIndexRoute
  '/research/evaluations/create/$projectId': typeof ResearchEvaluationsCreateProjectIdRoute
  '/research/ideas/$id/director': typeof ResearchIdeasIdDirectorRoute
  '/research/ideas/$id/edit': typeof ResearchIdeasIdEditRoute
  '/research/ideas/$id/workspace': typeof ResearchIdeasIdWorkspaceRoute
  '/research/projects/create/$ideaId': typeof ResearchProjectsCreateIdeaIdRoute
  '/research/screenings/create/$ideaId': typeof ResearchScreeningsCreateIdeaIdRoute
  '/research/transfers/create/$projectId': typeof ResearchTransfersCreateProjectIdRoute
  '/research/ideas/$id/': typeof ResearchIdeasIdIndexRoute
  '/research/ideas/$id/workflow/$progressId/review': typeof ResearchIdeasIdWorkflowProgressIdReviewRoute
  '/research/ideas/$id/workflow/$progressId/work': typeof ResearchIdeasIdWorkflowProgressIdWorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/cloud': typeof CloudRoute
  '/cybersecurity': typeof CybersecurityRoute
  '/development': typeof DevelopmentRoute
  '/duplication': typeof DuplicationRoute
  '/feasibility': typeof FeasibilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/infrastructure': typeof InfrastructureRoute
  '/institution-register': typeof InstitutionRegisterRoute
  '/login': typeof LoginRoute
  '/permissions': typeof PermissionsRoute
  '/projects': typeof ProjectsRoute
  '/quality': typeof QualityRoute
  '/rbac': typeof RbacRoute
  '/reports': typeof ReportsRoute
  '/security-review': typeof SecurityReviewRoute
  '/settings': typeof SettingsRoute
  '/surveys': typeof SurveysRoute
  '/tasks': typeof TasksRoute
  '/training': typeof TrainingRoute
  '/workflows': typeof WorkflowsRoute
  '/dashboard/auditor': typeof DashboardAuditorRoute
  '/dashboard/bureau-head': typeof DashboardBureauHeadRoute
  '/dashboard/executive': typeof DashboardExecutiveRoute
  '/dashboard/institution': typeof DashboardInstitutionRoute
  '/dashboard/licensing': typeof DashboardLicensingRoute
  '/dashboard/main': typeof DashboardMainRoute
  '/dashboard/no-access': typeof DashboardNoAccessRoute
  '/dashboard/research': typeof DashboardResearchRoute
  '/dashboard/subcity': typeof DashboardSubcityRoute
  '/dashboard/technology-transfer': typeof DashboardTechnologyTransferRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/registry/create': typeof RegistryCreateRoute
  '/requests/assigned': typeof RequestsAssignedRoute
  '/requests/create': typeof RequestsCreateRoute
  '/research/assigned': typeof ResearchAssignedRoute
  '/research/assignments': typeof ResearchAssignmentsRoute
  '/research/evaluations': typeof ResearchEvaluationsRouteWithChildren
  '/research/projects': typeof ResearchProjectsRouteWithChildren
  '/research/reports': typeof ResearchReportsRoute
  '/research/screenings': typeof ResearchScreeningsRouteWithChildren
  '/research/team': typeof ResearchTeamRoute
  '/research/transfers': typeof ResearchTransfersRouteWithChildren
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tickets/create': typeof TicketsCreateRoute
  '/users/create': typeof UsersCreateRoute
  '/vendors/create': typeof VendorsCreateRoute
  '/dashboard': typeof DashboardIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/registry': typeof RegistryIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/service-requests': typeof ServiceRequestsIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/users': typeof UsersIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/registry/$id/edit': typeof RegistryIdEditRoute
  '/requests/$id/edit': typeof RequestsIdEditRoute
  '/research/ideas/create': typeof ResearchIdeasCreateRoute
  '/research/ideas/director': typeof ResearchIdeasDirectorRoute
  '/research/ideas/team-leader': typeof ResearchIdeasTeamLeaderRoute
  '/research/officer/assessments': typeof ResearchOfficerAssessmentsRoute
  '/research/officer/assignments': typeof ResearchOfficerAssignmentsRoute
  '/research/officer/dashboard': typeof ResearchOfficerDashboardRoute
  '/research/officer/documents': typeof ResearchOfficerDocumentsRoute
  '/research/officer/stages': typeof ResearchOfficerStagesRoute
  '/research/officer/submissions': typeof ResearchOfficerSubmissionsRoute
  '/research/projects/$id': typeof ResearchProjectsIdRoute
  '/research/team-leader/dashboard': typeof ResearchTeamLeaderDashboardRoute
  '/research/team-leader/reviews': typeof ResearchTeamLeaderReviewsRoute
  '/service-requests/$id/workspace': typeof ServiceRequestsIdWorkspaceRoute
  '/users/$id/edit': typeof UsersIdEditRoute
  '/research/ideas': typeof ResearchIdeasIndexRoute
  '/service-requests/$id': typeof ServiceRequestsIdIndexRoute
  '/research/evaluations/create/$projectId': typeof ResearchEvaluationsCreateProjectIdRoute
  '/research/ideas/$id/director': typeof ResearchIdeasIdDirectorRoute
  '/research/ideas/$id/edit': typeof ResearchIdeasIdEditRoute
  '/research/ideas/$id/workspace': typeof ResearchIdeasIdWorkspaceRoute
  '/research/projects/create/$ideaId': typeof ResearchProjectsCreateIdeaIdRoute
  '/research/screenings/create/$ideaId': typeof ResearchScreeningsCreateIdeaIdRoute
  '/research/transfers/create/$projectId': typeof ResearchTransfersCreateProjectIdRoute
  '/research/ideas/$id': typeof ResearchIdeasIdIndexRoute
  '/research/ideas/$id/workflow/$progressId/review': typeof ResearchIdeasIdWorkflowProgressIdReviewRoute
  '/research/ideas/$id/workflow/$progressId/work': typeof ResearchIdeasIdWorkflowProgressIdWorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/cloud': typeof CloudRoute
  '/cybersecurity': typeof CybersecurityRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/development': typeof DevelopmentRoute
  '/duplication': typeof DuplicationRoute
  '/feasibility': typeof FeasibilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/infrastructure': typeof InfrastructureRoute
  '/institution-register': typeof InstitutionRegisterRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/permissions': typeof PermissionsRoute
  '/projects': typeof ProjectsRoute
  '/quality': typeof QualityRoute
  '/rbac': typeof RbacRoute
  '/registry': typeof RegistryRouteWithChildren
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRouteWithChildren
  '/security-review': typeof SecurityReviewRoute
  '/service-requests': typeof ServiceRequestsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/surveys': typeof SurveysRoute
  '/tasks': typeof TasksRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/training': typeof TrainingRoute
  '/users': typeof UsersRouteWithChildren
  '/vendors': typeof VendorsRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/dashboard/auditor': typeof DashboardAuditorRoute
  '/dashboard/bureau-head': typeof DashboardBureauHeadRoute
  '/dashboard/executive': typeof DashboardExecutiveRoute
  '/dashboard/institution': typeof DashboardInstitutionRoute
  '/dashboard/licensing': typeof DashboardLicensingRoute
  '/dashboard/main': typeof DashboardMainRoute
  '/dashboard/no-access': typeof DashboardNoAccessRoute
  '/dashboard/research': typeof DashboardResearchRoute
  '/dashboard/subcity': typeof DashboardSubcityRoute
  '/dashboard/technology-transfer': typeof DashboardTechnologyTransferRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/registry/create': typeof RegistryCreateRoute
  '/requests/assigned': typeof RequestsAssignedRoute
  '/requests/create': typeof RequestsCreateRoute
  '/research/assigned': typeof ResearchAssignedRoute
  '/research/assignments': typeof ResearchAssignmentsRoute
  '/research/evaluations': typeof ResearchEvaluationsRouteWithChildren
  '/research/ideas': typeof ResearchIdeasRouteWithChildren
  '/research/projects': typeof ResearchProjectsRouteWithChildren
  '/research/reports': typeof ResearchReportsRoute
  '/research/screenings': typeof ResearchScreeningsRouteWithChildren
  '/research/team': typeof ResearchTeamRoute
  '/research/transfers': typeof ResearchTransfersRouteWithChildren
  '/service-requests/$id': typeof ServiceRequestsIdRouteWithChildren
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tickets/create': typeof TicketsCreateRoute
  '/users/create': typeof UsersCreateRoute
  '/vendors/create': typeof VendorsCreateRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/registry/': typeof RegistryIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/service-requests/': typeof ServiceRequestsIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/registry/$id/edit': typeof RegistryIdEditRoute
  '/requests/$id/edit': typeof RequestsIdEditRoute
  '/research/ideas/$id': typeof ResearchIdeasIdRouteWithChildren
  '/research/ideas/create': typeof ResearchIdeasCreateRoute
  '/research/ideas/director': typeof ResearchIdeasDirectorRoute
  '/research/ideas/team-leader': typeof ResearchIdeasTeamLeaderRoute
  '/research/officer/assessments': typeof ResearchOfficerAssessmentsRoute
  '/research/officer/assignments': typeof ResearchOfficerAssignmentsRoute
  '/research/officer/dashboard': typeof ResearchOfficerDashboardRoute
  '/research/officer/documents': typeof ResearchOfficerDocumentsRoute
  '/research/officer/stages': typeof ResearchOfficerStagesRoute
  '/research/officer/submissions': typeof ResearchOfficerSubmissionsRoute
  '/research/projects/$id': typeof ResearchProjectsIdRoute
  '/research/team-leader/dashboard': typeof ResearchTeamLeaderDashboardRoute
  '/research/team-leader/reviews': typeof ResearchTeamLeaderReviewsRoute
  '/service-requests/$id/workspace': typeof ServiceRequestsIdWorkspaceRoute
  '/users/$id/edit': typeof UsersIdEditRoute
  '/research/ideas/': typeof ResearchIdeasIndexRoute
  '/service-requests/$id/': typeof ServiceRequestsIdIndexRoute
  '/research/evaluations/create/$projectId': typeof ResearchEvaluationsCreateProjectIdRoute
  '/research/ideas/$id/director': typeof ResearchIdeasIdDirectorRoute
  '/research/ideas/$id/edit': typeof ResearchIdeasIdEditRoute
  '/research/ideas/$id/workspace': typeof ResearchIdeasIdWorkspaceRoute
  '/research/projects/create/$ideaId': typeof ResearchProjectsCreateIdeaIdRoute
  '/research/screenings/create/$ideaId': typeof ResearchScreeningsCreateIdeaIdRoute
  '/research/transfers/create/$projectId': typeof ResearchTransfersCreateProjectIdRoute
  '/research/ideas/$id/': typeof ResearchIdeasIdIndexRoute
  '/research/ideas/$id/workflow/$progressId/review': typeof ResearchIdeasIdWorkflowProgressIdReviewRoute
  '/research/ideas/$id/workflow/$progressId/work': typeof ResearchIdeasIdWorkflowProgressIdWorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/cloud'
    | '/cybersecurity'
    | '/dashboard'
    | '/development'
    | '/duplication'
    | '/feasibility'
    | '/forgot-password'
    | '/infrastructure'
    | '/institution-register'
    | '/login'
    | '/notifications'
    | '/permissions'
    | '/projects'
    | '/quality'
    | '/rbac'
    | '/registry'
    | '/reports'
    | '/requests'
    | '/security-review'
    | '/service-requests'
    | '/settings'
    | '/surveys'
    | '/tasks'
    | '/tickets'
    | '/training'
    | '/users'
    | '/vendors'
    | '/workflows'
    | '/dashboard/auditor'
    | '/dashboard/bureau-head'
    | '/dashboard/executive'
    | '/dashboard/institution'
    | '/dashboard/licensing'
    | '/dashboard/main'
    | '/dashboard/no-access'
    | '/dashboard/research'
    | '/dashboard/subcity'
    | '/dashboard/technology-transfer'
    | '/documents/$id'
    | '/registry/create'
    | '/requests/assigned'
    | '/requests/create'
    | '/research/assigned'
    | '/research/assignments'
    | '/research/evaluations'
    | '/research/ideas'
    | '/research/projects'
    | '/research/reports'
    | '/research/screenings'
    | '/research/team'
    | '/research/transfers'
    | '/service-requests/$id'
    | '/services/$serviceSlug'
    | '/tickets/$id'
    | '/tickets/create'
    | '/users/create'
    | '/vendors/create'
    | '/dashboard/'
    | '/notifications/'
    | '/profile/'
    | '/registry/'
    | '/requests/'
    | '/service-requests/'
    | '/tickets/'
    | '/users/'
    | '/vendors/'
    | '/registry/$id/edit'
    | '/requests/$id/edit'
    | '/research/ideas/$id'
    | '/research/ideas/create'
    | '/research/ideas/director'
    | '/research/ideas/team-leader'
    | '/research/officer/assessments'
    | '/research/officer/assignments'
    | '/research/officer/dashboard'
    | '/research/officer/documents'
    | '/research/officer/stages'
    | '/research/officer/submissions'
    | '/research/projects/$id'
    | '/research/team-leader/dashboard'
    | '/research/team-leader/reviews'
    | '/service-requests/$id/workspace'
    | '/users/$id/edit'
    | '/research/ideas/'
    | '/service-requests/$id/'
    | '/research/evaluations/create/$projectId'
    | '/research/ideas/$id/director'
    | '/research/ideas/$id/edit'
    | '/research/ideas/$id/workspace'
    | '/research/projects/create/$ideaId'
    | '/research/screenings/create/$ideaId'
    | '/research/transfers/create/$projectId'
    | '/research/ideas/$id/'
    | '/research/ideas/$id/workflow/$progressId/review'
    | '/research/ideas/$id/workflow/$progressId/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/cloud'
    | '/cybersecurity'
    | '/development'
    | '/duplication'
    | '/feasibility'
    | '/forgot-password'
    | '/infrastructure'
    | '/institution-register'
    | '/login'
    | '/permissions'
    | '/projects'
    | '/quality'
    | '/rbac'
    | '/reports'
    | '/security-review'
    | '/settings'
    | '/surveys'
    | '/tasks'
    | '/training'
    | '/workflows'
    | '/dashboard/auditor'
    | '/dashboard/bureau-head'
    | '/dashboard/executive'
    | '/dashboard/institution'
    | '/dashboard/licensing'
    | '/dashboard/main'
    | '/dashboard/no-access'
    | '/dashboard/research'
    | '/dashboard/subcity'
    | '/dashboard/technology-transfer'
    | '/documents/$id'
    | '/registry/create'
    | '/requests/assigned'
    | '/requests/create'
    | '/research/assigned'
    | '/research/assignments'
    | '/research/evaluations'
    | '/research/projects'
    | '/research/reports'
    | '/research/screenings'
    | '/research/team'
    | '/research/transfers'
    | '/services/$serviceSlug'
    | '/tickets/$id'
    | '/tickets/create'
    | '/users/create'
    | '/vendors/create'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/registry'
    | '/requests'
    | '/service-requests'
    | '/tickets'
    | '/users'
    | '/vendors'
    | '/registry/$id/edit'
    | '/requests/$id/edit'
    | '/research/ideas/create'
    | '/research/ideas/director'
    | '/research/ideas/team-leader'
    | '/research/officer/assessments'
    | '/research/officer/assignments'
    | '/research/officer/dashboard'
    | '/research/officer/documents'
    | '/research/officer/stages'
    | '/research/officer/submissions'
    | '/research/projects/$id'
    | '/research/team-leader/dashboard'
    | '/research/team-leader/reviews'
    | '/service-requests/$id/workspace'
    | '/users/$id/edit'
    | '/research/ideas'
    | '/service-requests/$id'
    | '/research/evaluations/create/$projectId'
    | '/research/ideas/$id/director'
    | '/research/ideas/$id/edit'
    | '/research/ideas/$id/workspace'
    | '/research/projects/create/$ideaId'
    | '/research/screenings/create/$ideaId'
    | '/research/transfers/create/$projectId'
    | '/research/ideas/$id'
    | '/research/ideas/$id/workflow/$progressId/review'
    | '/research/ideas/$id/workflow/$progressId/work'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/cloud'
    | '/cybersecurity'
    | '/dashboard'
    | '/development'
    | '/duplication'
    | '/feasibility'
    | '/forgot-password'
    | '/infrastructure'
    | '/institution-register'
    | '/login'
    | '/notifications'
    | '/permissions'
    | '/projects'
    | '/quality'
    | '/rbac'
    | '/registry'
    | '/reports'
    | '/requests'
    | '/security-review'
    | '/service-requests'
    | '/settings'
    | '/surveys'
    | '/tasks'
    | '/tickets'
    | '/training'
    | '/users'
    | '/vendors'
    | '/workflows'
    | '/dashboard/auditor'
    | '/dashboard/bureau-head'
    | '/dashboard/executive'
    | '/dashboard/institution'
    | '/dashboard/licensing'
    | '/dashboard/main'
    | '/dashboard/no-access'
    | '/dashboard/research'
    | '/dashboard/subcity'
    | '/dashboard/technology-transfer'
    | '/documents/$id'
    | '/registry/create'
    | '/requests/assigned'
    | '/requests/create'
    | '/research/assigned'
    | '/research/assignments'
    | '/research/evaluations'
    | '/research/ideas'
    | '/research/projects'
    | '/research/reports'
    | '/research/screenings'
    | '/research/team'
    | '/research/transfers'
    | '/service-requests/$id'
    | '/services/$serviceSlug'
    | '/tickets/$id'
    | '/tickets/create'
    | '/users/create'
    | '/vendors/create'
    | '/dashboard/'
    | '/notifications/'
    | '/profile/'
    | '/registry/'
    | '/requests/'
    | '/service-requests/'
    | '/tickets/'
    | '/users/'
    | '/vendors/'
    | '/registry/$id/edit'
    | '/requests/$id/edit'
    | '/research/ideas/$id'
    | '/research/ideas/create'
    | '/research/ideas/director'
    | '/research/ideas/team-leader'
    | '/research/officer/assessments'
    | '/research/officer/assignments'
    | '/research/officer/dashboard'
    | '/research/officer/documents'
    | '/research/officer/stages'
    | '/research/officer/submissions'
    | '/research/projects/$id'
    | '/research/team-leader/dashboard'
    | '/research/team-leader/reviews'
    | '/service-requests/$id/workspace'
    | '/users/$id/edit'
    | '/research/ideas/'
    | '/service-requests/$id/'
    | '/research/evaluations/create/$projectId'
    | '/research/ideas/$id/director'
    | '/research/ideas/$id/edit'
    | '/research/ideas/$id/workspace'
    | '/research/projects/create/$ideaId'
    | '/research/screenings/create/$ideaId'
    | '/research/transfers/create/$projectId'
    | '/research/ideas/$id/'
    | '/research/ideas/$id/workflow/$progressId/review'
    | '/research/ideas/$id/workflow/$progressId/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CloudRoute: typeof CloudRoute
  CybersecurityRoute: typeof CybersecurityRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DevelopmentRoute: typeof DevelopmentRoute
  DuplicationRoute: typeof DuplicationRoute
  FeasibilityRoute: typeof FeasibilityRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InfrastructureRoute: typeof InfrastructureRoute
  InstitutionRegisterRoute: typeof InstitutionRegisterRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRouteWithChildren
  PermissionsRoute: typeof PermissionsRoute
  ProjectsRoute: typeof ProjectsRoute
  QualityRoute: typeof QualityRoute
  RbacRoute: typeof RbacRoute
  RegistryRoute: typeof RegistryRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  RequestsRoute: typeof RequestsRouteWithChildren
  SecurityReviewRoute: typeof SecurityReviewRoute
  ServiceRequestsRoute: typeof ServiceRequestsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SurveysRoute: typeof SurveysRoute
  TasksRoute: typeof TasksRoute
  TicketsRoute: typeof TicketsRouteWithChildren
  TrainingRoute: typeof TrainingRoute
  UsersRoute: typeof UsersRouteWithChildren
  VendorsRoute: typeof VendorsRouteWithChildren
  WorkflowsRoute: typeof WorkflowsRoute
  DocumentsIdRoute: typeof DocumentsIdRoute
  ResearchAssignedRoute: typeof ResearchAssignedRoute
  ResearchAssignmentsRoute: typeof ResearchAssignmentsRoute
  ResearchEvaluationsRoute: typeof ResearchEvaluationsRouteWithChildren
  ResearchIdeasRoute: typeof ResearchIdeasRouteWithChildren
  ResearchProjectsRoute: typeof ResearchProjectsRouteWithChildren
  ResearchReportsRoute: typeof ResearchReportsRoute
  ResearchScreeningsRoute: typeof ResearchScreeningsRouteWithChildren
  ResearchTeamRoute: typeof ResearchTeamRoute
  ResearchTransfersRoute: typeof ResearchTransfersRouteWithChildren
  ServicesServiceSlugRoute: typeof ServicesServiceSlugRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ResearchOfficerAssessmentsRoute: typeof ResearchOfficerAssessmentsRoute
  ResearchOfficerAssignmentsRoute: typeof ResearchOfficerAssignmentsRoute
  ResearchOfficerDashboardRoute: typeof ResearchOfficerDashboardRoute
  ResearchOfficerDocumentsRoute: typeof ResearchOfficerDocumentsRoute
  ResearchOfficerStagesRoute: typeof ResearchOfficerStagesRoute
  ResearchOfficerSubmissionsRoute: typeof ResearchOfficerSubmissionsRoute
  ResearchTeamLeaderDashboardRoute: typeof ResearchTeamLeaderDashboardRoute
  ResearchTeamLeaderReviewsRoute: typeof ResearchTeamLeaderReviewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-requests': {
      id: '/service-requests'
      path: '/service-requests'
      fullPath: '/service-requests'
      preLoaderRoute: typeof ServiceRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-review': {
      id: '/security-review'
      path: '/security-review'
      fullPath: '/security-review'
      preLoaderRoute: typeof SecurityReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rbac': {
      id: '/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof RbacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution-register': {
      id: '/institution-register'
      path: '/institution-register'
      fullPath: '/institution-register'
      preLoaderRoute: typeof InstitutionRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feasibility': {
      id: '/feasibility'
      path: '/feasibility'
      fullPath: '/feasibility'
      preLoaderRoute: typeof FeasibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplication': {
      id: '/duplication'
      path: '/duplication'
      fullPath: '/duplication'
      preLoaderRoute: typeof DuplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurity': {
      id: '/cybersecurity'
      path: '/cybersecurity'
      fullPath: '/cybersecurity'
      preLoaderRoute: typeof CybersecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/service-requests/': {
      id: '/service-requests/'
      path: '/'
      fullPath: '/service-requests/'
      preLoaderRoute: typeof ServiceRequestsIndexRouteImport
      parentRoute: typeof ServiceRequestsRoute
    }
    '/requests/': {
      id: '/requests/'
      path: '/'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/registry/': {
      id: '/registry/'
      path: '/'
      fullPath: '/registry/'
      preLoaderRoute: typeof RegistryIndexRouteImport
      parentRoute: typeof RegistryRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/vendors/create': {
      id: '/vendors/create'
      path: '/create'
      fullPath: '/vendors/create'
      preLoaderRoute: typeof VendorsCreateRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/users/create': {
      id: '/users/create'
      path: '/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof UsersCreateRouteImport
      parentRoute: typeof UsersRoute
    }
    '/tickets/create': {
      id: '/tickets/create'
      path: '/create'
      fullPath: '/tickets/create'
      preLoaderRoute: typeof TicketsCreateRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/services/$serviceSlug': {
      id: '/services/$serviceSlug'
      path: '/services/$serviceSlug'
      fullPath: '/services/$serviceSlug'
      preLoaderRoute: typeof ServicesServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-requests/$id': {
      id: '/service-requests/$id'
      path: '/$id'
      fullPath: '/service-requests/$id'
      preLoaderRoute: typeof ServiceRequestsIdRouteImport
      parentRoute: typeof ServiceRequestsRoute
    }
    '/research/transfers': {
      id: '/research/transfers'
      path: '/research/transfers'
      fullPath: '/research/transfers'
      preLoaderRoute: typeof ResearchTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/team': {
      id: '/research/team'
      path: '/research/team'
      fullPath: '/research/team'
      preLoaderRoute: typeof ResearchTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/screenings': {
      id: '/research/screenings'
      path: '/research/screenings'
      fullPath: '/research/screenings'
      preLoaderRoute: typeof ResearchScreeningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/reports': {
      id: '/research/reports'
      path: '/research/reports'
      fullPath: '/research/reports'
      preLoaderRoute: typeof ResearchReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/projects': {
      id: '/research/projects'
      path: '/research/projects'
      fullPath: '/research/projects'
      preLoaderRoute: typeof ResearchProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/ideas': {
      id: '/research/ideas'
      path: '/research/ideas'
      fullPath: '/research/ideas'
      preLoaderRoute: typeof ResearchIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/evaluations': {
      id: '/research/evaluations'
      path: '/research/evaluations'
      fullPath: '/research/evaluations'
      preLoaderRoute: typeof ResearchEvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/assignments': {
      id: '/research/assignments'
      path: '/research/assignments'
      fullPath: '/research/assignments'
      preLoaderRoute: typeof ResearchAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/assigned': {
      id: '/research/assigned'
      path: '/research/assigned'
      fullPath: '/research/assigned'
      preLoaderRoute: typeof ResearchAssignedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/create': {
      id: '/requests/create'
      path: '/create'
      fullPath: '/requests/create'
      preLoaderRoute: typeof RequestsCreateRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/requests/assigned': {
      id: '/requests/assigned'
      path: '/assigned'
      fullPath: '/requests/assigned'
      preLoaderRoute: typeof RequestsAssignedRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/registry/create': {
      id: '/registry/create'
      path: '/create'
      fullPath: '/registry/create'
      preLoaderRoute: typeof RegistryCreateRouteImport
      parentRoute: typeof RegistryRoute
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/technology-transfer': {
      id: '/dashboard/technology-transfer'
      path: '/technology-transfer'
      fullPath: '/dashboard/technology-transfer'
      preLoaderRoute: typeof DashboardTechnologyTransferRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subcity': {
      id: '/dashboard/subcity'
      path: '/subcity'
      fullPath: '/dashboard/subcity'
      preLoaderRoute: typeof DashboardSubcityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/research': {
      id: '/dashboard/research'
      path: '/research'
      fullPath: '/dashboard/research'
      preLoaderRoute: typeof DashboardResearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/no-access': {
      id: '/dashboard/no-access'
      path: '/no-access'
      fullPath: '/dashboard/no-access'
      preLoaderRoute: typeof DashboardNoAccessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/main': {
      id: '/dashboard/main'
      path: '/main'
      fullPath: '/dashboard/main'
      preLoaderRoute: typeof DashboardMainRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/licensing': {
      id: '/dashboard/licensing'
      path: '/licensing'
      fullPath: '/dashboard/licensing'
      preLoaderRoute: typeof DashboardLicensingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/institution': {
      id: '/dashboard/institution'
      path: '/institution'
      fullPath: '/dashboard/institution'
      preLoaderRoute: typeof DashboardInstitutionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/executive': {
      id: '/dashboard/executive'
      path: '/executive'
      fullPath: '/dashboard/executive'
      preLoaderRoute: typeof DashboardExecutiveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bureau-head': {
      id: '/dashboard/bureau-head'
      path: '/bureau-head'
      fullPath: '/dashboard/bureau-head'
      preLoaderRoute: typeof DashboardBureauHeadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/auditor': {
      id: '/dashboard/auditor'
      path: '/auditor'
      fullPath: '/dashboard/auditor'
      preLoaderRoute: typeof DashboardAuditorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/service-requests/$id/': {
      id: '/service-requests/$id/'
      path: '/'
      fullPath: '/service-requests/$id/'
      preLoaderRoute: typeof ServiceRequestsIdIndexRouteImport
      parentRoute: typeof ServiceRequestsIdRoute
    }
    '/research/ideas/': {
      id: '/research/ideas/'
      path: '/'
      fullPath: '/research/ideas/'
      preLoaderRoute: typeof ResearchIdeasIndexRouteImport
      parentRoute: typeof ResearchIdeasRoute
    }
    '/users/$id/edit': {
      id: '/users/$id/edit'
      path: '/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof UsersIdEditRouteImport
      parentRoute: typeof UsersRoute
    }
    '/service-requests/$id/workspace': {
      id: '/service-requests/$id/workspace'
      path: '/workspace'
      fullPath: '/service-requests/$id/workspace'
      preLoaderRoute: typeof ServiceRequestsIdWorkspaceRouteImport
      parentRoute: typeof ServiceRequestsIdRoute
    }
    '/research/team-leader/reviews': {
      id: '/research/team-leader/reviews'
      path: '/research/team-leader/reviews'
      fullPath: '/research/team-leader/reviews'
      preLoaderRoute: typeof ResearchTeamLeaderReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/team-leader/dashboard': {
      id: '/research/team-leader/dashboard'
      path: '/research/team-leader/dashboard'
      fullPath: '/research/team-leader/dashboard'
      preLoaderRoute: typeof ResearchTeamLeaderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/projects/$id': {
      id: '/research/projects/$id'
      path: '/$id'
      fullPath: '/research/projects/$id'
      preLoaderRoute: typeof ResearchProjectsIdRouteImport
      parentRoute: typeof ResearchProjectsRoute
    }
    '/research/officer/submissions': {
      id: '/research/officer/submissions'
      path: '/research/officer/submissions'
      fullPath: '/research/officer/submissions'
      preLoaderRoute: typeof ResearchOfficerSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/officer/stages': {
      id: '/research/officer/stages'
      path: '/research/officer/stages'
      fullPath: '/research/officer/stages'
      preLoaderRoute: typeof ResearchOfficerStagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/officer/documents': {
      id: '/research/officer/documents'
      path: '/research/officer/documents'
      fullPath: '/research/officer/documents'
      preLoaderRoute: typeof ResearchOfficerDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/officer/dashboard': {
      id: '/research/officer/dashboard'
      path: '/research/officer/dashboard'
      fullPath: '/research/officer/dashboard'
      preLoaderRoute: typeof ResearchOfficerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/officer/assignments': {
      id: '/research/officer/assignments'
      path: '/research/officer/assignments'
      fullPath: '/research/officer/assignments'
      preLoaderRoute: typeof ResearchOfficerAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/officer/assessments': {
      id: '/research/officer/assessments'
      path: '/research/officer/assessments'
      fullPath: '/research/officer/assessments'
      preLoaderRoute: typeof ResearchOfficerAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/ideas/team-leader': {
      id: '/research/ideas/team-leader'
      path: '/team-leader'
      fullPath: '/research/ideas/team-leader'
      preLoaderRoute: typeof ResearchIdeasTeamLeaderRouteImport
      parentRoute: typeof ResearchIdeasRoute
    }
    '/research/ideas/director': {
      id: '/research/ideas/director'
      path: '/director'
      fullPath: '/research/ideas/director'
      preLoaderRoute: typeof ResearchIdeasDirectorRouteImport
      parentRoute: typeof ResearchIdeasRoute
    }
    '/research/ideas/create': {
      id: '/research/ideas/create'
      path: '/create'
      fullPath: '/research/ideas/create'
      preLoaderRoute: typeof ResearchIdeasCreateRouteImport
      parentRoute: typeof ResearchIdeasRoute
    }
    '/research/ideas/$id': {
      id: '/research/ideas/$id'
      path: '/$id'
      fullPath: '/research/ideas/$id'
      preLoaderRoute: typeof ResearchIdeasIdRouteImport
      parentRoute: typeof ResearchIdeasRoute
    }
    '/requests/$id/edit': {
      id: '/requests/$id/edit'
      path: '/$id/edit'
      fullPath: '/requests/$id/edit'
      preLoaderRoute: typeof RequestsIdEditRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/registry/$id/edit': {
      id: '/registry/$id/edit'
      path: '/$id/edit'
      fullPath: '/registry/$id/edit'
      preLoaderRoute: typeof RegistryIdEditRouteImport
      parentRoute: typeof RegistryRoute
    }
    '/research/ideas/$id/': {
      id: '/research/ideas/$id/'
      path: '/'
      fullPath: '/research/ideas/$id/'
      preLoaderRoute: typeof ResearchIdeasIdIndexRouteImport
      parentRoute: typeof ResearchIdeasIdRoute
    }
    '/research/transfers/create/$projectId': {
      id: '/research/transfers/create/$projectId'
      path: '/create/$projectId'
      fullPath: '/research/transfers/create/$projectId'
      preLoaderRoute: typeof ResearchTransfersCreateProjectIdRouteImport
      parentRoute: typeof ResearchTransfersRoute
    }
    '/research/screenings/create/$ideaId': {
      id: '/research/screenings/create/$ideaId'
      path: '/create/$ideaId'
      fullPath: '/research/screenings/create/$ideaId'
      preLoaderRoute: typeof ResearchScreeningsCreateIdeaIdRouteImport
      parentRoute: typeof ResearchScreeningsRoute
    }
    '/research/projects/create/$ideaId': {
      id: '/research/projects/create/$ideaId'
      path: '/create/$ideaId'
      fullPath: '/research/projects/create/$ideaId'
      preLoaderRoute: typeof ResearchProjectsCreateIdeaIdRouteImport
      parentRoute: typeof ResearchProjectsRoute
    }
    '/research/ideas/$id/workspace': {
      id: '/research/ideas/$id/workspace'
      path: '/workspace'
      fullPath: '/research/ideas/$id/workspace'
      preLoaderRoute: typeof ResearchIdeasIdWorkspaceRouteImport
      parentRoute: typeof ResearchIdeasIdRoute
    }
    '/research/ideas/$id/edit': {
      id: '/research/ideas/$id/edit'
      path: '/edit'
      fullPath: '/research/ideas/$id/edit'
      preLoaderRoute: typeof ResearchIdeasIdEditRouteImport
      parentRoute: typeof ResearchIdeasIdRoute
    }
    '/research/ideas/$id/director': {
      id: '/research/ideas/$id/director'
      path: '/director'
      fullPath: '/research/ideas/$id/director'
      preLoaderRoute: typeof ResearchIdeasIdDirectorRouteImport
      parentRoute: typeof ResearchIdeasIdRoute
    }
    '/research/evaluations/create/$projectId': {
      id: '/research/evaluations/create/$projectId'
      path: '/create/$projectId'
      fullPath: '/research/evaluations/create/$projectId'
      preLoaderRoute: typeof ResearchEvaluationsCreateProjectIdRouteImport
      parentRoute: typeof ResearchEvaluationsRoute
    }
    '/research/ideas/$id/workflow/$progressId/work': {
      id: '/research/ideas/$id/workflow/$progressId/work'
      path: '/workflow/$progressId/work'
      fullPath: '/research/ideas/$id/workflow/$progressId/work'
      preLoaderRoute: typeof ResearchIdeasIdWorkflowProgressIdWorkRouteImport
      parentRoute: typeof ResearchIdeasIdRoute
    }
    '/research/ideas/$id/workflow/$progressId/review': {
      id: '/research/ideas/$id/workflow/$progressId/review'
      path: '/workflow/$progressId/review'
      fullPath: '/research/ideas/$id/workflow/$progressId/review'
      preLoaderRoute: typeof ResearchIdeasIdWorkflowProgressIdReviewRouteImport
      parentRoute: typeof ResearchIdeasIdRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAuditorRoute: typeof DashboardAuditorRoute
  DashboardBureauHeadRoute: typeof DashboardBureauHeadRoute
  DashboardExecutiveRoute: typeof DashboardExecutiveRoute
  DashboardInstitutionRoute: typeof DashboardInstitutionRoute
  DashboardLicensingRoute: typeof DashboardLicensingRoute
  DashboardMainRoute: typeof DashboardMainRoute
  DashboardNoAccessRoute: typeof DashboardNoAccessRoute
  DashboardResearchRoute: typeof DashboardResearchRoute
  DashboardSubcityRoute: typeof DashboardSubcityRoute
  DashboardTechnologyTransferRoute: typeof DashboardTechnologyTransferRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAuditorRoute: DashboardAuditorRoute,
  DashboardBureauHeadRoute: DashboardBureauHeadRoute,
  DashboardExecutiveRoute: DashboardExecutiveRoute,
  DashboardInstitutionRoute: DashboardInstitutionRoute,
  DashboardLicensingRoute: DashboardLicensingRoute,
  DashboardMainRoute: DashboardMainRoute,
  DashboardNoAccessRoute: DashboardNoAccessRoute,
  DashboardResearchRoute: DashboardResearchRoute,
  DashboardSubcityRoute: DashboardSubcityRoute,
  DashboardTechnologyTransferRoute: DashboardTechnologyTransferRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface NotificationsRouteChildren {
  NotificationsIndexRoute: typeof NotificationsIndexRoute
}

const NotificationsRouteChildren: NotificationsRouteChildren = {
  NotificationsIndexRoute: NotificationsIndexRoute,
}

const NotificationsRouteWithChildren = NotificationsRoute._addFileChildren(
  NotificationsRouteChildren,
)

interface RegistryRouteChildren {
  RegistryCreateRoute: typeof RegistryCreateRoute
  RegistryIndexRoute: typeof RegistryIndexRoute
  RegistryIdEditRoute: typeof RegistryIdEditRoute
}

const RegistryRouteChildren: RegistryRouteChildren = {
  RegistryCreateRoute: RegistryCreateRoute,
  RegistryIndexRoute: RegistryIndexRoute,
  RegistryIdEditRoute: RegistryIdEditRoute,
}

const RegistryRouteWithChildren = RegistryRoute._addFileChildren(
  RegistryRouteChildren,
)

interface RequestsRouteChildren {
  RequestsAssignedRoute: typeof RequestsAssignedRoute
  RequestsCreateRoute: typeof RequestsCreateRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  RequestsIdEditRoute: typeof RequestsIdEditRoute
}

const RequestsRouteChildren: RequestsRouteChildren = {
  RequestsAssignedRoute: RequestsAssignedRoute,
  RequestsCreateRoute: RequestsCreateRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  RequestsIdEditRoute: RequestsIdEditRoute,
}

const RequestsRouteWithChildren = RequestsRoute._addFileChildren(
  RequestsRouteChildren,
)

interface ServiceRequestsIdRouteChildren {
  ServiceRequestsIdWorkspaceRoute: typeof ServiceRequestsIdWorkspaceRoute
  ServiceRequestsIdIndexRoute: typeof ServiceRequestsIdIndexRoute
}

const ServiceRequestsIdRouteChildren: ServiceRequestsIdRouteChildren = {
  ServiceRequestsIdWorkspaceRoute: ServiceRequestsIdWorkspaceRoute,
  ServiceRequestsIdIndexRoute: ServiceRequestsIdIndexRoute,
}

const ServiceRequestsIdRouteWithChildren =
  ServiceRequestsIdRoute._addFileChildren(ServiceRequestsIdRouteChildren)

interface ServiceRequestsRouteChildren {
  ServiceRequestsIdRoute: typeof ServiceRequestsIdRouteWithChildren
  ServiceRequestsIndexRoute: typeof ServiceRequestsIndexRoute
}

const ServiceRequestsRouteChildren: ServiceRequestsRouteChildren = {
  ServiceRequestsIdRoute: ServiceRequestsIdRouteWithChildren,
  ServiceRequestsIndexRoute: ServiceRequestsIndexRoute,
}

const ServiceRequestsRouteWithChildren = ServiceRequestsRoute._addFileChildren(
  ServiceRequestsRouteChildren,
)

interface TicketsRouteChildren {
  TicketsIdRoute: typeof TicketsIdRoute
  TicketsCreateRoute: typeof TicketsCreateRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsIdRoute: TicketsIdRoute,
  TicketsCreateRoute: TicketsCreateRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

interface UsersRouteChildren {
  UsersCreateRoute: typeof UsersCreateRoute
  UsersIndexRoute: typeof UsersIndexRoute
  UsersIdEditRoute: typeof UsersIdEditRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersCreateRoute: UsersCreateRoute,
  UsersIndexRoute: UsersIndexRoute,
  UsersIdEditRoute: UsersIdEditRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface VendorsRouteChildren {
  VendorsCreateRoute: typeof VendorsCreateRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

const VendorsRouteChildren: VendorsRouteChildren = {
  VendorsCreateRoute: VendorsCreateRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}

const VendorsRouteWithChildren =
  VendorsRoute._addFileChildren(VendorsRouteChildren)

interface ResearchEvaluationsRouteChildren {
  ResearchEvaluationsCreateProjectIdRoute: typeof ResearchEvaluationsCreateProjectIdRoute
}

const ResearchEvaluationsRouteChildren: ResearchEvaluationsRouteChildren = {
  ResearchEvaluationsCreateProjectIdRoute:
    ResearchEvaluationsCreateProjectIdRoute,
}

const ResearchEvaluationsRouteWithChildren =
  ResearchEvaluationsRoute._addFileChildren(ResearchEvaluationsRouteChildren)

interface ResearchIdeasIdRouteChildren {
  ResearchIdeasIdDirectorRoute: typeof ResearchIdeasIdDirectorRoute
  ResearchIdeasIdEditRoute: typeof ResearchIdeasIdEditRoute
  ResearchIdeasIdWorkspaceRoute: typeof ResearchIdeasIdWorkspaceRoute
  ResearchIdeasIdIndexRoute: typeof ResearchIdeasIdIndexRoute
  ResearchIdeasIdWorkflowProgressIdReviewRoute: typeof ResearchIdeasIdWorkflowProgressIdReviewRoute
  ResearchIdeasIdWorkflowProgressIdWorkRoute: typeof ResearchIdeasIdWorkflowProgressIdWorkRoute
}

const ResearchIdeasIdRouteChildren: ResearchIdeasIdRouteChildren = {
  ResearchIdeasIdDirectorRoute: ResearchIdeasIdDirectorRoute,
  ResearchIdeasIdEditRoute: ResearchIdeasIdEditRoute,
  ResearchIdeasIdWorkspaceRoute: ResearchIdeasIdWorkspaceRoute,
  ResearchIdeasIdIndexRoute: ResearchIdeasIdIndexRoute,
  ResearchIdeasIdWorkflowProgressIdReviewRoute:
    ResearchIdeasIdWorkflowProgressIdReviewRoute,
  ResearchIdeasIdWorkflowProgressIdWorkRoute:
    ResearchIdeasIdWorkflowProgressIdWorkRoute,
}

const ResearchIdeasIdRouteWithChildren = ResearchIdeasIdRoute._addFileChildren(
  ResearchIdeasIdRouteChildren,
)

interface ResearchIdeasRouteChildren {
  ResearchIdeasIdRoute: typeof ResearchIdeasIdRouteWithChildren
  ResearchIdeasCreateRoute: typeof ResearchIdeasCreateRoute
  ResearchIdeasDirectorRoute: typeof ResearchIdeasDirectorRoute
  ResearchIdeasTeamLeaderRoute: typeof ResearchIdeasTeamLeaderRoute
  ResearchIdeasIndexRoute: typeof ResearchIdeasIndexRoute
}

const ResearchIdeasRouteChildren: ResearchIdeasRouteChildren = {
  ResearchIdeasIdRoute: ResearchIdeasIdRouteWithChildren,
  ResearchIdeasCreateRoute: ResearchIdeasCreateRoute,
  ResearchIdeasDirectorRoute: ResearchIdeasDirectorRoute,
  ResearchIdeasTeamLeaderRoute: ResearchIdeasTeamLeaderRoute,
  ResearchIdeasIndexRoute: ResearchIdeasIndexRoute,
}

const ResearchIdeasRouteWithChildren = ResearchIdeasRoute._addFileChildren(
  ResearchIdeasRouteChildren,
)

interface ResearchProjectsRouteChildren {
  ResearchProjectsIdRoute: typeof ResearchProjectsIdRoute
  ResearchProjectsCreateIdeaIdRoute: typeof ResearchProjectsCreateIdeaIdRoute
}

const ResearchProjectsRouteChildren: ResearchProjectsRouteChildren = {
  ResearchProjectsIdRoute: ResearchProjectsIdRoute,
  ResearchProjectsCreateIdeaIdRoute: ResearchProjectsCreateIdeaIdRoute,
}

const ResearchProjectsRouteWithChildren =
  ResearchProjectsRoute._addFileChildren(ResearchProjectsRouteChildren)

interface ResearchScreeningsRouteChildren {
  ResearchScreeningsCreateIdeaIdRoute: typeof ResearchScreeningsCreateIdeaIdRoute
}

const ResearchScreeningsRouteChildren: ResearchScreeningsRouteChildren = {
  ResearchScreeningsCreateIdeaIdRoute: ResearchScreeningsCreateIdeaIdRoute,
}

const ResearchScreeningsRouteWithChildren =
  ResearchScreeningsRoute._addFileChildren(ResearchScreeningsRouteChildren)

interface ResearchTransfersRouteChildren {
  ResearchTransfersCreateProjectIdRoute: typeof ResearchTransfersCreateProjectIdRoute
}

const ResearchTransfersRouteChildren: ResearchTransfersRouteChildren = {
  ResearchTransfersCreateProjectIdRoute: ResearchTransfersCreateProjectIdRoute,
}

const ResearchTransfersRouteWithChildren =
  ResearchTransfersRoute._addFileChildren(ResearchTransfersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CloudRoute: CloudRoute,
  CybersecurityRoute: CybersecurityRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DevelopmentRoute: DevelopmentRoute,
  DuplicationRoute: DuplicationRoute,
  FeasibilityRoute: FeasibilityRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InfrastructureRoute: InfrastructureRoute,
  InstitutionRegisterRoute: InstitutionRegisterRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRouteWithChildren,
  PermissionsRoute: PermissionsRoute,
  ProjectsRoute: ProjectsRoute,
  QualityRoute: QualityRoute,
  RbacRoute: RbacRoute,
  RegistryRoute: RegistryRouteWithChildren,
  ReportsRoute: ReportsRoute,
  RequestsRoute: RequestsRouteWithChildren,
  SecurityReviewRoute: SecurityReviewRoute,
  ServiceRequestsRoute: ServiceRequestsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SurveysRoute: SurveysRoute,
  TasksRoute: TasksRoute,
  TicketsRoute: TicketsRouteWithChildren,
  TrainingRoute: TrainingRoute,
  UsersRoute: UsersRouteWithChildren,
  VendorsRoute: VendorsRouteWithChildren,
  WorkflowsRoute: WorkflowsRoute,
  DocumentsIdRoute: DocumentsIdRoute,
  ResearchAssignedRoute: ResearchAssignedRoute,
  ResearchAssignmentsRoute: ResearchAssignmentsRoute,
  ResearchEvaluationsRoute: ResearchEvaluationsRouteWithChildren,
  ResearchIdeasRoute: ResearchIdeasRouteWithChildren,
  ResearchProjectsRoute: ResearchProjectsRouteWithChildren,
  ResearchReportsRoute: ResearchReportsRoute,
  ResearchScreeningsRoute: ResearchScreeningsRouteWithChildren,
  ResearchTeamRoute: ResearchTeamRoute,
  ResearchTransfersRoute: ResearchTransfersRouteWithChildren,
  ServicesServiceSlugRoute: ServicesServiceSlugRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ResearchOfficerAssessmentsRoute: ResearchOfficerAssessmentsRoute,
  ResearchOfficerAssignmentsRoute: ResearchOfficerAssignmentsRoute,
  ResearchOfficerDashboardRoute: ResearchOfficerDashboardRoute,
  ResearchOfficerDocumentsRoute: ResearchOfficerDocumentsRoute,
  ResearchOfficerStagesRoute: ResearchOfficerStagesRoute,
  ResearchOfficerSubmissionsRoute: ResearchOfficerSubmissionsRoute,
  ResearchTeamLeaderDashboardRoute: ResearchTeamLeaderDashboardRoute,
  ResearchTeamLeaderReviewsRoute: ResearchTeamLeaderReviewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
